### ISSUE TITLE
Generate just one connector package: .zip or .tar.gz

### ISSUE THREAD

**Issue by valdar** [apache/camel-kafka-connector#1030]
Given the number of connectors we have, releasing and packaging them in 2 formats is just a waste of time and resources, nowadays all modern operating systems should be able to handle `.zip` or `.tar.gz` archives indifferently.

Just remove one of the formats.

**Comment by oscerd** [comment]
We'll remove the .tar.gz one.

**Comment by tadayosi** [comment]
Right now Strimzi seems to support only `*.tar.gz`, so probably keeping `*.tar.gz` makes more sense.
https://strimzi.io/docs/operators/master/using.html#plugins

**Comment by oscerd** [comment]
I guess zip is supported too https://github.com/strimzi/strimzi-kafka-operator/blob/master/install/cluster-operator/041-Crd-kafkaconnect.yaml#L1908

**Comment by tadayosi** [comment]
Ah cool. Then I'm fine with zip, too.

**Comment by oscerd** [comment]
I'm asking for confirmation, I have the PR ready for this :-)

**Comment by oscerd** [comment]
@scholzj provided some feedback, zip will be supported from the next release, so since we are planning to release this weekend, I'll change the PR to only generate tar.gz
