### ISSUE TITLE
Not able to add resource file

### ISSUE THREAD

**Issue by ruchirvaninasdaq** [apache/camel-kafka-connector#104]
Hello, 

I am trying to create the AvroSeralizer for the S3 object. I have to add schema files in the resource folder.
https://github.com/apache/camel-kafka-connector/tree/master/core/src/main 

But after the jar is built, I am not able to read the resource folder, Is there anything you have to change in pom.xml? so it can include the schema file at run time.

Thanks

**Comment by oscerd** [comment]
What have you done?

**Comment by ruchirvaninasdaq** [comment]
Created the classes to get schema, but still not able to read to resource folder.

**Comment by valdar** [comment]
@ruchirvaninasdaq could you share a project with what you have added to better understand what you would like to achieve and try to help the best we can?
