### ISSUE TITLE
ITests don't work when a test class is specified with `-Dtest=...`

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-kafka-connector#1062]
For instance, this works:
```
mvn -DskipIntegrationTests=false verify -pl tests/itests-timer
```
but this doesn't:
```
mvn -DskipIntegrationTests=false -Dtest=CamelSourceTimerITCase verify -pl tests/itests-timer
```

Looking at the `target/tests.log` I can see these lines:

> 2021-02-25 12:22:38,065 [main           ] DEBUG org.apache.camel.kafkaconnector.common.PluginPathHelper - Base dir used for search: /home/tasato/projects/apache/camel-kafka-connector/tests/itests-timer/null/connectors/camel-timer-kafka-connector
> 2021-02-25 12:22:38,067 [main           ] INFO org.apache.camel.kafkaconnector.common.PluginPathHelper - Returning the following directories for the plugin path: 

so this code from PluginPathHelper doesn't work well when a test runs with `-Dtest=...`. The system property `project.basedir` doesn't seem to be always reliable.
```java
            String path = System.getProperty("project.basedir") + File.separator + module;
```

**Comment by ffang** [comment]
Hi @tadayosi,

Please try with "-Dit.test=" instead of "-Dtest="
It's failsafe plugin, not the surefire plugin which launch the test.

Cheers
Freeman

**Comment by tadayosi** [comment]
@ffang Thanks! Yes, you're correct. It's resolved.
