### ISSUE TITLE
`camel.source.endpoint.sync` issue in CamelInfinispanSourceConnector in 0.8.0

### ISSUE THREAD

**Issue by apupier** [apache/camel-kafka-connector#1068]
in 0.7.2, th eoption was part of the catalog https://github.com/apache/camel-kafka-connector/blob/b756e8adf915e2b523fc40c160ae51b3353582e9/camel-kafka-connector-catalog/src/generated/resources/connectors/camel-infinispan-source.json#L70

it has been removed in 0.8.0 https://github.com/apache/camel-kafka-connector/blob/camel-kafka-connector-0.8.0/camel-kafka-connector-catalog/src/generated/resources/connectors/camel-infinispan-source.json

but it is still used in examples:

https://github.com/apache/camel-kafka-connector-examples/blob/7bb7ea2326712075751d703476ea31a85f9bdbec/infinispan/infinispan-source/config/CamelInfinispanSourceConnector.properties#L28

https://github.com/apache/camel-kafka-connector-examples/blob/7bb7ea2326712075751d703476ea31a85f9bdbec/infinispan/infinispan-source-with-authentication/config/CamelInfinispanSourceConnector.properties#L28

Is it that the option is missing from the catalog definition? or that it shoudl be removed from the example?

**Comment by oscerd** [comment]
It is in infinispan-embedded component. In 3.8.x the component has been splitted in two different components, infinispan and infinispan-embedded, the infinispan one is for the remote part and there is no sync anymore. I'll review the examples.

**Comment by oscerd** [comment]
This is an examples related problem, so let me close this and lets continue in examples. Thanks for reporting.
