### ISSUE TITLE
Google pub/sub: endpoint option cannot be set

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#1086]
When trying to set the connector using URL:

```2021-03-05 12:30:57,807 [lGooglePubSub-0] ERROR org.apache.camel.processor.errorhandler.DefaultErrorHandler - Failed delivery for (MessageId: FEA0554C87763BA-0000000000000000 on ExchangeId: FEA0554C87763BA-0000000000000000). Exhausted after delivery attempt: 1 caught: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: google-pubsub://ckc:ckctopic53?endpoint=localhost:32791 due to: Failed to resolve endpoint: google-pubsub://ckc:ckctopic53?endpoint=localhost:32791 due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{endpoint=localhost:32791}]```

**Comment by oscerd** [comment]
What option are you using, because the endpoint is configurable only at component level

camel.component.google-pubsub.endpoint

**Comment by orpiske** [comment]
Thanks @oscerd! Setting the endpoint at the component level solved the issue.
