### ISSUE TITLE
NetworkUtils should be able to hold a free port for later usage

### ISSUE THREAD

**Issue by ffang** [apache/camel-kafka-connector#1109]
Currently the starting port is always 45152, this can cause a problem in scenario like

1. In my test I check 45152 as a free port, so I define a PORT to refer it in my class INIT code; and I use it later and not bind to this listening port immediately 
2. Another thread(Like Kafka service) check 45152 as a free port and bind to it 
3. I my test when I really need to use this PORT, I get "Address already bind" exception

I think we should move up starting port for each time when a free port is checked and pinned for later usage to avoid such conflicts

**Comment by ffang** [comment]
Open a PR
https://github.com/apache/camel-kafka-connector/pull/1111

**Comment by tadayosi** [comment]
Fixed with #1111
