### ISSUE TITLE
camel-mongodb-kafka-connector produce message format error

### ISSUE THREAD

**Issue by yingbo-wu** [apache/camel-kafka-connector#1113]
The “camel.source.endpoint.consumerType” is changeStreams
```
{
    ......
    "camel.source.endpoint.consumerType": "changeStreams",
    ......
}
```

The kafka topic message format is:
Document{{_id=6054153bb0c98c76191cd377, sfdc_id=a0L2x000001GjBgEAK, field_3=Fri Mar 05 00:00:00 GMT 2021, field_1=123, field_2=123}}

The format is that the "Document" object toString() returns something
Such a data format cannot be used downstream

**Comment by yingbo-wu** [comment]
"value.converter": "org.apache.kafka.connect.storage.StringConverter"

**Comment by yingbo-wu** [comment]
My solution is
```
"value.converter": "org.apache.kafka.connect.json.JsonConverter",
"camel.source.marshal": "org.apache.camel.component.gson.GsonDataFormat",
```
But, The official example is "value.converter": "org.apache.kafka.connect.storage.StringConverter"

**Comment by oscerd** [comment]
The pojo returned is always Document. You can transform it in json by unmarshalling it with json-jackson dataformat which is provided out of the box and by default in all the connectors. Thanks.
