### ISSUE TITLE
camel-minio-kafka-connector can't split minio file

### ISSUE THREAD

**Issue by songlingling0012** [apache/camel-kafka-connector#1124]
no matter how big the minio file , it maked as one message to kafka topic.
i want split minio file content by '\n',one splitted  as one kafka message.
how could i do?

**Comment by oscerd** [comment]
This is how the underline component works, so you can't split it at the moment.

**Comment by songlingling0012** [comment]
Thanks for your reply! 
I modified the source codes by overriding the poll() method , I got SourceRecord and splitted it's content.
Is there a downside to this？

**Comment by oscerd** [comment]
No, the problem is it won't work if you use different connectors

**Comment by songlingling0012** [comment]
I see... 
I'm just using the minio-connector for my project, so it doesn't matter.
But I got a new problem,the  minio file that I already readed don't deleted or removed

**Comment by valdar** [comment]
@songlingling0012 what version of `camel-kafka-conenctor` are you using? and how have you modified the `poll()` method? 

I suspect you might have crippled the exchange completion upon commit mechanism.
