### ISSUE TITLE
Align master to latest camel snapshot

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#1133]
We seen that is almost impossible to keep the two branch in sync, because of generated docs.

So we need to:
- make the website documentation point to the 0.9.x branch and publish that documentation without latest
- Move master to point to 3.10.0-SNAPSHOT
- Build camel each night a rebuild the ckc master based on it
- Fix errors arising

In the long term this would mean an easier maintenance.

**Comment by oscerd** [comment]
https://github.com/apache/camel-website/pull/562 for the website

**Comment by oscerd** [comment]
master point to snapshot of camel master.
website should publish from 0.9.x branch.
camel-master is still there for checking if we have things to backport @orpiske 
On 0.9.x we have to change the version and set to 0.9.1-SNAPSHOT if we are going to have a minor release for something not backported from camel-master.
I changed the gh action and now it will build master with camel 3.10.0-SNAPSHOT and eventually open a PR on master branch. 
You can safely ignore camel-master, we'll remove it once verified everything has been backported.

**Comment by orpiske** [comment]
@oscerd thanks! I took a look at it recently and I think all the backports have been merged already. Therefore, we are good to go.
