### ISSUE TITLE
Salesforce Sink Connector does not honour `offset.flush.interval.ms`

### ISSUE THREAD

**Issue by tmus** [apache/camel-kafka-connector#1181]
Setting `offset.flush.interval.ms` on the connector config does not result in any change to the rate at which the offsets are flushed.

This falls back to using the default 60s defined by Connect.

Attempting to override using `consumer.override.offset.flush.interval.ms` also does not result in any change.

**Comment by oscerd** [comment]
Did you find a solution?

**Comment by TomEijk** [comment]
Hi! I'm encountering the same error at the moment. Could you please explain the solution you found for overriding this default value in `offset.flush.interval.ms`?
