### ISSUE TITLE
CAMEL-AWS-KINESIS-KAFKA-CONNECTOR SOURCE CONFIGURATION

### ISSUE THREAD

**Issue by m4nuC** [apache/camel-kafka-connector#1186]
Hi,

I am trying to use the kinesis source connector to copy kinesis data to a Kafka stream. 

I copy the `camel-aws-kinesis-kafka-connector-0.7.1.jar` but the class does not seem to be available in the Kafka connect.

The documentation mentions adding:

```
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-aws-kinesis-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
```

but not knowing much java I am unsure what to do with this. Am I missing one step ? 

Thanka a lot

**Comment by oscerd** [comment]
Hello,

Can you please report the steps you're following please?

Thank you

**Comment by m4nuC** [comment]
Hi, 

Thank you for the fast reply.

The steps are:
1. I download the [connector]( https://repo.maven.apache.org/maven2/org/apache/camel/kafkaconnector/camel-aws2-kinesis-kafka-connector/0.9.0/camel-aws2-kinesis-kafka-connector-0.9.0-package.tar.gz)
2. I unzip it and copy the `camel-aws-kinesis-kafka-connecto`r folder inside kafka connect` class path` using a dockerfile
3. I start the application and try to strat a connector with the class: `org.apache.camel.kafkaconnector.aws2kinesis.CamelAws2kinesisSourceConnector` and I will get a class not found error

Am I missing anything ? 

Thanks a lot

**Comment by oscerd** [comment]
I personally don't have so much experience with confluent hub. 

You can have a look at the examples we provide on plain kafka: https://github.com/apache/camel-kafka-connector-examples/tree/main/aws2-kinesis

**Comment by m4nuC** [comment]
@oscerd thanks, that helps. In that example, do you know what is meant by:  `import the ftp-extended project`

**Comment by oscerd** [comment]
@m4nuC you can safely ignore the ftp-extended part (a typo by the way).

The SMT for Kinesis is already included in the connector jar.

https://github.com/apache/camel-kafka-connector/blob/main/connectors/camel-aws2-kinesis-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/aws2kinesis/transformers/KinesisRecordDataTransforms.java

Please use the latest released version 0.10.0, just follow the example, ignoring the maven archetype generation part, just use the connector you downloaded and the configuration provided.

Let us know.

**Comment by oscerd** [comment]
It has been released you can find it in maven central.

**Comment by oscerd** [comment]
You need to specify the transform in the configuration. You are using the byte array converter. can you please post your configuration?

**Comment by m4nuC** [comment]
@oscerd Indeed I have not yet added the transform in the connector config. Let me look up 0.10.0 first then I will report back

**Comment by m4nuC** [comment]
0.9.0 when adding the transform errored out saying it could not fine the `org.apache.camel.kafkaconnector.KinesisRecordDataTransforms` class

**Comment by m4nuC** [comment]
Same error with 0.10.0. I can create the connector without the transform with the following config:

```
connector.class=org.apache.camel.kafkaconnector.aws2kinesis.CamelAws2kinesisSourceConnector
tasks.max=1
topics=_topic
camel.source.endpoint.region=eu-north-1
camel.source.endpoint.accessKey=hhhhhh
camel.source.endpoint.secretKey=hhhhhh
value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
camel.source.path.streamName=kinesis_test
```

but if I add the transform it will faill with the following error:

`Invalid value org.apache.camel.kafkaconnector.KinesisRecordDataTransforms for configuration transforms.KinesisRecordDataTransforms.type: Class org.apache.camel.kafkaconnector.KinesisRecordDataTransforms could not be found`

**Comment by oscerd** [comment]
I guess the package is different now for the transform. I'll get back to you

**Comment by oscerd** [comment]
So instead of 

```
transforms=KinesisRecordDataTransforms
transforms.KinesisRecordDataTransforms.type=org.apache.camel.kafkaconnector.KinesisRecordDataTransforms
```

Now it is

```
transforms=KinesisRecordDataTransforms
transforms.KinesisRecordDataTransforms.type=org.apache.camel.kafkaconnector.aws2kinesis.transformers.KinesisRecordDataTransforms
```

Sorry for this, we need to update docs and examples.

**Comment by m4nuC** [comment]
Thanks, @oscerd. Otherwise, building the transform from the template that you referenced is OK should that be easier but I am unsure where to grab that template from

**Comment by oscerd** [comment]
Can you post your complete configuration?

**Comment by m4nuC** [comment]
@oscerd would you have the source code for the `KinesisRecordDataTransforms` handy by any chance? I would like to adapt it to output byte array rather than string

**Comment by oscerd** [comment]
https://github.com/apache/camel-kafka-connector/blob/main/connectors/camel-aws2-kinesis-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/aws2kinesis/transformers/KinesisRecordDataTransforms.java

**Comment by m4nuC** [comment]
Ah, I should totally have found that on my own.. Thanks!

**Comment by oscerd** [comment]
If your use case could be a general one, you can even propose a PR and we could add the SMT in the connector.
