### ISSUE TITLE
Missing kafkaconnector parent pom artifact for version 0.10.0

### ISSUE THREAD

**Issue by lhein** [apache/camel-kafka-connector#1190]
It seems there was something wrong with the 0.10.0 release because I am unable to find `org.apache.camel.kafkaconnector:parent:0.10.0`. Its neither available from the ASF M2 Repo nor from Maven central.

https://repo1.maven.org/maven2/org/apache/camel/kafkaconnector/parent/
https://repository.apache.org/content/groups/public/org/apache/camel/kafkaconnector/parent/

**Comment by valdar** [comment]
I fear a new release (`0.10.1`) is needed to fix this.

**Comment by oscerd** [comment]
This has been fixed with 0.10.1
