### ISSUE TITLE
aws2s3 source connector split file into several messages 

### ISSUE THREAD

**Issue by anna842** [apache/camel-kafka-connector#1196]
Hi,
I would like to use AWS2 S3 sink and source connectors in order to save some currently not needed data to s3 and read it later if needed.
As Kafka topics can be big and write/read operations in S3 cost money, I am using aggregate strategy when writing data to S3:
```
        "connector.class": "org.apache.camel.kafkaconnector.aws2s3.CamelAws2s3SinkConnector",
        "topics": "some_topic",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "camel.sink.path.bucketNameOrArn": "my-bucket",
        "camel.sink.endpoint.region": "eu-west-1",
        "camel.sink.endpoint.keyName": "${date:now:yyyy-MM-dd}/${date:now:yyyy-MM-dd-HH:mm:ss:SSS}.json",
        "value.converter":"org.apache.kafka.connect.json.JsonConverter",
        "camel.sink.marshal": "org.apache.camel.component.jackson.JacksonDataFormat",
        "value.converter.schemas.enable":"false",
        "camel.beans.aggregate": "#class:org.apache.camel.kafkaconnector.aggregator.StringAggregator",
        "camel.aggregation.size": "500",
        "camel.aggregation.timeout": "2000"
```
But when I am reading files back to Kafka with s3 source connector, every file becomes one large message.
My current source connector configuration:
```
        "connector.class": "org.apache.camel.kafkaconnector.aws2s3.CamelAws2s3SourceConnector",
        "topics": "some_topic_from_s3",
        "tasks.max": "1",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "camel.source.path.bucketNameOrArn": "my-bucket",
        "camel.source.endpoint.region": "eu-west-1",
        "camel.source.endpoint.prefix":"2021-06-07",
        "value.converter":"org.apache.kafka.connect.converters.ByteArrayConverter"
```
Is it possible to split aggregated messages?
If not, is it planned to implement this feature? What workaround would you recommend for now?

**Comment by oscerd** [comment]
There is no support for Split at the moment, but If you need to do something like this, it makes really much more sense to use plain Camel.

**Comment by venkat-oss** [comment]
@oscerd I have a question, for the "camel.sink.endpoint.keyName", I tried something like this : "${date:now:yyyy-MM-dd}-${headers[kafka.TOPIC]}" and I got a simple language exception, how can we access kafka headers from the exchange?

**Comment by oscerd** [comment]
${header.kafka.TOPIC}

Please don't hijack issues from other users.

**Comment by venkat-oss** [comment]
@oscerd my bad, sorry for that, i'll open a fresh issue next time 👍🏼

**Comment by anna842** [comment]
Ok, thank you for the answer.
