### ISSUE TITLE
Java bean error when using aws2-s3-source connector

### ISSUE THREAD

**Issue by arjun180** [apache/camel-kafka-connector#1217]
Hello,

I'm working on getting the aws2s3 source connector to work. But it's throwing a Java bean error on on of the parameters. I used a similar set of parameters when I was configuring my sink connector. And that works just fine. 

Error : 

```
Caused by: org.apache.camel.PropertyBindingException: Error binding property (camel.component.aws2-s3.useDefaultCredentials Provider=true) with name: useDefaultCredentials Provider on bean: org.apache.camel.component.aws2.s3.AWS2S3Component@72daf76 with value: true

```

My Kafka Connector yaml file : 

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: s3-source-connector
  labels:
    strimzi.io/cluster:my-connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.aws2s3.CamelAws2s3SourceConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.S3ObjectConverter
    topics: my-topic 
    camel.source.path.bucketNameOrArn: my-cluster-connect
    camel.source.endpoint.useDefaultCredentials Provider: true
    camel.component.aws2-s3.useDefaultCredentials Provider: true
    camel.component.aws2-s3.fileName: <file-name>
    camel.source.endpoint.region: <region>
```

When I was working on the sink connector, I had to change the permissions of the IAM to create the EC2 instance of the pod and give it access to the s3 bucket (https://github.com/apache/camel-kafka-connector/issues/282). I was wondering if there was something I needed to change on the s3 bucket side of things?

Appreciate the help

**Comment by oscerd** [comment]
You need to set the property on the endpoint OR on the component not both

**Comment by arjun180** [comment]
Yeah, actually when I removed the space in the name of the property - I got an error 
```
Caused by: [software.amazon.awssdk.services.s3.model.NoSuchKeyException - The specified key does not exist. (Service: S3, Status Code: 404, Request ID: XTGWDN3HVMPJ1B0T, Extended Request ID: havB9SNeqYAV9zU2m2R1Abcd3bpz2XH8BRGzxlcHehXAP7vxk8l1/mCMfugTndIj0MLjMxp9yrU=)] (org.apache.camel.component.aws2.s3.AWS2S3Consumer) 
```
I double checked here and the space was present?
 https://camel.apache.org/camel-kafka-connector/latest/reference/connectors/camel-aws2-s3-kafka-source-connector.html

**Comment by oscerd** [comment]
The space is just for formatting the table. It's one long string.

**Comment by oscerd** [comment]
The error seems you are pointing a file that doesn't exist in the bucket

**Comment by arjun180** [comment]
Oh I see! It got to working when I only kept only the ```camel.component.aws2-s3.useDefaultCredentialsProvider: true```. Thank you for your help. I'll close the issue.
