### ISSUE TITLE
Is it possible to attach Custom Processor to existing Connector?

### ISSUE THREAD

**Issue by ohadpinch** [apache/camel-kafka-connector#1228]
I have a project in which I want to use CamelHTTPSinkConnector and to be able to log the HTTP response and send it via dedicated Kafka topic.

I thought it can be done by attaching custom Processor, but I don't know how.

Thanks,
Ohad Pinchevsky

**Comment by oscerd** [comment]
Do you mean a custom Camel processor?

**Comment by oscerd** [comment]
If you need to add a processor step, it makes sense to use plain Camel and not camel-kafka-connector.

**Comment by ohadpinch** [comment]
So, if not using Processor, is there other way to add business logic (such as logging) to existing camel-kafka-connector?

**Comment by oscerd** [comment]
Try to use

https://camel.apache.org/camel-kafka-connector/latest/user-guide/basic-configuration.html

camel.sink.contentLogLevel

**Comment by ohadpinch** [comment]
Thanks,  What if I also want to send the HTTP response to Kafka topic?

**Comment by oscerd** [comment]
Do you mean you want to do something like this?

Consume a record from a kafka topic -> send the record content to an http endpoint -> capture the http response -> send to a different topic?

**Comment by ohadpinch** [comment]
Exactly

**Comment by oscerd** [comment]
I don't think there is a possibility to do this, once you sent the request to the http endpoint you're not able to access the response anymore, this is because of how kafka connect works. 

Even using an SMT won't help, because it would kick in before the sink connector and not after.

Maybe you can use the kafka connect reporter feature, to check successful and failing http requests and redirect them to differen t topics.

**Comment by ohadpinch** [comment]
Thanks, I'll check it out

**Comment by ohadpinch** [comment]
Can you please redirect me to Camel documentation for reporter feature?

**Comment by oscerd** [comment]
https://kafka.apache.org/documentation/#connect

It's a connect connect. Search for errant record reporter.

There is also documentation on the confluent website.

**Comment by oscerd** [comment]
And this example too
https://github.com/apache/camel-kafka-connector-examples/tree/main/other-examples/error-handling-sink

**Comment by ohadpinch** [comment]
Thanks, I see it handles errors, how can I get the response in success cases?

**Comment by oscerd** [comment]
I don't think there is a way with plain Kafka. My suggestion is to move to plain camel if you need to inspect the response

**Comment by ohadpinch** [comment]
I need to think about it, It might an architecture constraint to use Kafka Connect.
I might need to create new connector if no other way.

**Comment by oscerd** [comment]
Did you manage to find a solution?

**Comment by ohadpinch** [comment]
I have added kafka producer and returned the result manually.
I worked with exchange.out obj and checked for failures.
