### ISSUE TITLE
Configurable parameters in AWS2-s3 Kafka source connector

### ISSUE THREAD

**Issue by arjun180** [apache/camel-kafka-connector#1247]
Is there anyway I can configure the `camel.source.endpoint.prefix` field based on the document [here](https://camel.apache.org/camel-kafka-connector/latest/reference/connectors/camel-aws2-s3-kafka-source-connector.html) to something like this : `camel.source.endpoint.prefix: 'connector-test/${date:now:yyyyMMdd}'`. I know something like that is possible for the Kafka sink and parameter `camel.sink.endpoint.keyName`. 

**Use case** : I have a Kafka connector which is supposed to pick up files from s3 bucket prefixes that get created everyday. If the `camel.source.endpoint.prefix` is not configurable, then what's the best way of handling such a situation?

Other configurations : 

- AWS s3 Kafka connector version : 0.10.1
- Kafka version : 2.8.0
- Strimzi has been used as the Kafka orchestrator

**Comment by oscerd** [comment]
It's not possible for technical reason related to Camel consumers.

**Comment by arjun180** [comment]
Got it. Thank you for your help
