### ISSUE TITLE
Bearer Token with HTTP sink?

### ISSUE THREAD

**Issue by kferrone** [apache/camel-kafka-connector#1255]
I am trying to use the HTTP sink connector: https://camel.apache.org/camel-kafka-connector/latest/reference/connectors/camel-http-kafka-sink-connector.html

The final endpoint I want to send the event to requires a bearer token in the header. However I do not see how it is possible to add the token to the header using the http sink connector. 

Is the HTTP connector the right one to use? It looks like this might be an option too: https://camel.apache.org/camel-kafka-connector/latest/reference/connectors/camel-rest-kafka-sink-connector.html

Context:
My goal is to send kafka events to the argo-workflows event endpoint. 
So this flow: produce kafka event --> kafka http sink connector handles event --> event is posted to argos event endpoint using bearer token

[Argo Workflows Events Endpoint](https://argoproj.github.io/argo-workflows/events/)

**Comment by oscerd** [comment]
Explained through this https://github.com/apache/camel-kafka-connector-examples/issues/323
