### ISSUE TITLE
Cannot findr camel-salesforce-source-kafka-connector in maven repository

### ISSUE THREAD

**Issue by milkchocolate** [apache/camel-kafka-connector#1284]
Hi team,

Is **camel-salesforce-source-kafka-connector** in maven repository?

I'm following the doc below
https://camel.apache.org/camel-kafka-connector/next/reference/connectors/camel-salesforce-source-kafka-source-connector.html

My IDE cannot download it, the IDE says "Cannot resolve org.apache.camel.kafkaconnector:camel-salesforce-source-kafka-connector:0.11.0"

I also checked it on https://mvnrepository.com/artifact/org.apache.camel.kafkaconnector, I can find "camel-salesforce-kafka-connector", but I cannot find "camel-salesforce-source-kafka-connector".

Can you help me on this?

**Comment by oscerd** [comment]
In Maven central you can find a single JAR for all the connectors. Inside there will the source and sink or just one of them.

In the jar you'll find the required classes. But for kafka-connect you don't need the jar directly, you'll need the package tar.gz to explode in your plugin path

https://repo1.maven.org/maven2/org/apache/camel/kafkaconnector/camel-salesforce-kafka-connector/0.11.0/camel-salesforce-kafka-connector-0.11.0-package.tar.gz

**Comment by milkchocolate** [comment]
This guide requires org.apache.camel.kafkaconnector.salesforcesource.CamelSalesforcesourceSourceConnector
https://camel.apache.org/camel-kafka-connector/next/reference/connectors/camel-salesforce-source-kafka-source-connector.html

Which I can find in the source code
![image](https://user-images.githubusercontent.com/5474821/140725582-930b5e8b-ef66-4073-b9fd-85b65abf37e8.png)

If I replace camel-salesforce-source-kafka-source-connector with camel-salesforce-kafka-source-connector. When I add the connector to Kafka, it says the CamelSalesforcesourceSourceConnector class can't be found.

If I extract the camel-salesforce-kafka-connector-0.11.0.jar, I can find CamelSalesforceSourceConnector, but I cannot find CamelSalesforce**source**SourceConnector. 
![image](https://user-images.githubusercontent.com/5474821/140726328-87635a43-3a3d-44ff-9852-f925a5c18086.png)

**Comment by oscerd** [comment]
You're referencing the next release. Change to 0.11.0 lts. The doc you're
using is referencing something still to release.

Il lun 8 nov 2021, 11:32 Yu, Nan ***@***.***> ha scritto:

**Comment by milkchocolate** [comment]
Thanks Andrea. Could you share the release plan with me?

**Comment by oscerd** [comment]
There is still no eta for the next release

**Comment by milkchocolate** [comment]
Is the camel-salesforce-source-kafka-source-connector ready? I maunally built the connecor and put it to the plugin folder, it works.

**Comment by oscerd** [comment]
It should work if you use the snapshot.

**Comment by milkchocolate** [comment]
Thanks Andrea
