### ISSUE TITLE
Unclean shutdown causing lots of warning messages in the logs

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#13]
When the test is shutting down, there are a lot of messages like this in the logs (~9k messages like this for a test run). 

`2019-12-08 20:24:49,992 [7c-6916da6c7843] WARN org.apache.kafka.clients.NetworkClient - [Producer clientId=6a23d856-c3d2-40b6-be7c-6916da6c7843] Connection to node 1 (localhost/127.0.0.1:34649) could not be established. Broker may not be available.`

This doesn't really affect anything, so probably low priority, but it seems to be fixed by a separate patch I am working on, so I may refer to this one when I send that one.

**Comment by orpiske** [comment]
Closing this one because it was fixed with the merge on #29.

**Comment by valdar** [comment]
Thanks! If you mention fix #issuenumber in the commit message it should close it automatically, I hope.
