### ISSUE TITLE
AWS Default Credential Provider is no longer available in 1.0?

### ISSUE THREAD

**Issue by jc43081** [apache/camel-kafka-connector#1331]
Previous to 1.0, the Default Credential Provider was able to be used for security credentials when connecting to AWS. It appears that with the pivot to Kamelets that this functionality is no longer available and [the only supported method is accesskey and secret](https://github.com/apache/camel-kafka-connector/blob/camel-kafka-connector-1.0.x/connectors/camel-aws-kinesis-sink-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/awskinesissink/CamelAwskinesissinkSinkConnectorConfig.java). As outlined within [AWS documentation](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html), the recommended method is to use the Default Credential Provider since it allows the most flexibility. 

Our company doesn't allow use of access keys and secrets but requires token based credentials. The [previous implementation supported this just fine](https://github.com/apache/camel-kafka-connector/blob/camel-kafka-connector-0.11.x/connectors/camel-aws2-kinesis-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/aws2kinesis/CamelAws2kinesisSinkConnectorConfig.java). Support of Default Credential Provider is essential to our continued adoption.

Is functionality planned to be added back in? If yes, when can it be expected? Thanks!

**Comment by oscerd** [comment]
It needs to be done at kamelet level in this case. Let me open an issue there

**Comment by oscerd** [comment]
https://github.com/apache/camel-kamelets/issues/735

**Comment by samudurand** [comment]
That's exactly what we noticed as well. We are using the SNS Kafka connector and it doesn't work if we don't provide explicit aws access key and secrets properties. The docs do not say what needs to be done to use the Default (EC2 based for instance) credentials providers. 
Assuming your changes just merged in Kamelet do fix that issue, what do we need to do to get it working ? 
Thank you!

**Comment by oscerd** [comment]
If you use the default credential provider parameter, the order will be the following: https://github.com/aws/aws-sdk-java-v2/blob/2.17.118/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.java#L24

It's up to you to satisfy one of this condition.

By the way, the fix is not completed, and for sure, we'll need a  new ckc release for 1.0.x

**Comment by shanhq96** [comment]
Hi, is there any updates on this issue? Seems the https://github.com/apache/camel-kamelets/issues/735 was already resolved

**Comment by oscerd** [comment]
We need to release 0.8.0 of camel-kamelets officially and after that we are going to release a version of camel-kafka-connector supporting it.
