### ISSUE TITLE
Use SNS Aws2 connector with AWS Default Credential Provider

### ISSUE THREAD

**Issue by samudurand** [apache/camel-kafka-connector#1335]
From the docs as well as the code of the Camel SNS AWS V2 provider I only see an Access Key and Access Secret settings. Is there any way to make the connector use the default AWS Credentials provider, so that it works on a standard EC2 instance ? 

When I do not provide the accessKey/accessSecret, then the connector fails with the error:
```
AmazonSNSClient or accessKey and secretKey must be specified
```

Does that mean it is possible to specify the client and make it use the default AWS Credentials provider? If yes, then how can I do so?

**Comment by oscerd** [comment]
It's not available yet. You need to wait for a new release for default credentials provider.

**Comment by samudurand** [comment]
Thanks for the quick answer. By the way where is the code for the AWSv2 SNS connector ? In this repo I could only see the code for the `aws` not `aws2` SNS connector. But I found a package with version 0.9 for it on the camel website.

**Comment by oscerd** [comment]
It's named aws but it's the AWS v2 SDK based, so you're looking at the right place.

**Comment by samudurand** [comment]
Thanks ! When you say we have to wait for the DefaultCredentialProvider to be available, are we talking about 1-3 weeks, or more like several months because it's not yet on your priority list ? I am just asking to evaluate our own options :)

**Comment by oscerd** [comment]
We don't have an ETA for this, but I think it could be in 3-4 weeks.
