### ISSUE TITLE
Support of PutEvents operation to CAMEL-AWS2-EVENTBRIDGE-KAFKA-CONNECTOR SINK

### ISSUE THREAD

**Issue by SumanRamakrishna** [apache/camel-kafka-connector#1384]
Hi,

I have a requirement to push the events from Kafka topic to AWS event bridge. Couldn't find any other connectors apart from camel-aws2-eventbridge-kafka-connector. So i wanted to give a try on camel connector. I went thru the documentation and found that this sink connector doesn't support putEvents operation.
<html>
<body>

camel.component.aws2-eventbridge.operation | The operation to perform One of: [putRule] [putTargets] [removeTargets] [deleteRule] [enableRule] [disableRule] [describeRule] [listRules] [listTargetsByRule] [listRuleNamesByTarget]
-- | --

</body>
</html>
 Could you please let me know any workaround for this or provide me inputs please?

**Comment by oscerd** [comment]
The putEvents operation will be available in Camel 3.19.0, so in a future version of camel-kafka-connector.
