### ISSUE TITLE
ignoreFileNotFoundOrPermissionError on camel-sftp-source 1.0.x

### ISSUE THREAD

**Issue by bsvicente** [apache/camel-kafka-connector#1385]
It's possible to use camel.source.endpoint.ignoreFileNotFoundOrPermissionError on 1.0.x LTS?

**Comment by oscerd** [comment]
We need to modify the Kamelet for this purpose.

**Comment by oscerd** [comment]
This has been fixed here: https://github.com/apache/camel-kamelets/pull/995

Once we'll update to the new Kamelet catalog and release the next camel kafka connector it will be available.

**Comment by bsvicente** [comment]
Perfect!
