### ISSUE TITLE
0.11.x CamelRabbitmqSourceConnector TrustManager Setting

### ISSUE THREAD

**Issue by Brentox** [apache/camel-kafka-connector#1416]
I am using the 0.11.x CamelRabbitmqSourceConnector connector with docker-compose and connect-standalone. I have things working in TCP but I would like to get it working in SSL. The docs mentions two settings: camel.component.rabbitmq.sslProtocol & camel.component.rabbitmq.trustManager. The first parameter is simple but trustManager is a little more confusing. I have the necessary certs to establish a secure connection, but how do I set up the trustmanager parameter/use it correctly?

**Comment by davsclaus** [comment]
closing old version tickets
