### ISSUE TITLE
Missing configuration parameters because of Kamelet

### ISSUE THREAD

**Issue by Do-min-ik** [apache/camel-kafka-connector#1417]
Hi there
I'm currently using version 1.0.0 to read from an FTP into Kafka. So far this works like a charm. However, there is a new requirement that I need to delete or rename my files after processing.

There is a configuration parameter called _delete_ in Camel, but it is not available in camel-ftp-source-kafka-connector. This is because version 1.0.0 is based on Kamelet which does not support the _delete_ configuration. It's possible to go back to version 0.11.x as it is based on the actual Camel component.

I know LTS support for 0.11.x ends this September and I guess version 1.0.x will be the only version moving forward as version 0.11.x is also based on an older version of Camel. Is this correct?

Version 1.0.x of camel-kafka-connector looks like an easier version to use but, unfortunately, also inferior at the same time. Am I missing something? 

I think the documentation needs a sentence or two regarding the dependency to Kamelet. I can create a pull request for that, though.

Cheers
Dominik

**Comment by brokenjacobs** [comment]
I'd like to know what's going on as well. I have an issue on the sink side where I need to make subdirectories and the old 0.11.x connector works but the new connector doesn't have a config property to create directories. What is the recommended path to take? I can't find a blog post or anything that talks about this kamlet conversion.

**Comment by oscerd** [comment]
The problem is we are not enough to cover all the possible corner cases, so we had to choose: killing this project or re-use what we already have, like Kamelets. So the choice was to re-use the building block for generating connector.

**Comment by oscerd** [comment]
The delete is available by the way, with version 4.4.2 https://github.com/apache/camel-kamelets/commit/94ca59002f87c2b6c0cfb1d2fd0134fdda21ce0b
