### ISSUE TITLE
Generate a table with supported connectors

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#142]
Since connectors are not real components, we may need to generate a model and borrowing information from the camel catalog.

**Comment by zregvart** [comment]
One option would be to utilize Asciidoc files, we can leverage page attributes and [`indexTable`](https://gitlab.com/djencks/asciidoctor-antora-indexer) macro, I think that would result in one `.adoc` file per connector. Another option could be to use data support in Hugo and generate a document or documents based on the JSON file from the catalog.
