### ISSUE TITLE
camel-rabbitmq-source-kafka-connector: Unable to specify vhost

### ISSUE THREAD

**Issue by steve-criticalmention** [apache/camel-kafka-connector#1442]
In version 3.18 of the `rabbitmq-source` Kafka connector, there is no option to specify the vhost to be used for RabbitMQ. This leads to errors like this:

```
Caused by: com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=530, reply-text=NOT_ALLOWED - access to vhost '/' refused for user 'guest', class-id=10, method-id=40)
```

I have tried to append the vhost to the addresses string, after the port specification, but that does not work:

```
[2022-10-04 22:34:54,673] ERROR [example|task-0] Error starting CamelContext (camel-1) due to exception thrown: For input string: "5672/custom_vhost" (org.apache.camel.impl.engine.AbstractCamelContext:3041)
[Worker-054b406375fec7d19] java.lang.NumberFormatException: For input string: "5672/custom_vhost"
```

Based on the [documentation from an older version](https://camel.apache.org/camel-kafka-connector/0.11.x/reference/connectors/camel-rabbitmq-kafka-source-connector.html) of the connector, it seems that vhost was able to be specified by using `camel.source.endpoint.vhost`, but based on [the most recent documentation](https://camel.apache.org/camel-kafka-connector/3.18.x/reference/connectors/camel-rabbitmq-source-kafka-source-connector.html), it seems that this setting is unavailable.

Is there any way to specify a RabbitMQ vhost using the `rabbitmq-source` Kafka connector in the most recent version? If there is, then it would be helpful to be documented, and if not, that would be a wonderful addition.

**Comment by oscerd** [comment]
This needs to be done at Kamelet level. In particular here: https://github.com/apache/camel-kamelets/blob/main/kamelets/rabbitmq-source.kamelet.yaml

**Comment by oscerd** [comment]
I'll try to add it in the next release.

**Comment by steve-criticalmention** [comment]
@oscerd, Thanks for your help.

When you specify the new option, is that because `vhost` is already part of the [camel-rabbitmq component](https://github.com/apache/camel/blob/main/components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQComponent.java#L55-L56)? Of these configuration options in the camel-rabbitmq component, are only the ones that can be added on the Kamelet level, options which don't have a hardcoded default value, and use `ConnectionFactory` as the default?

With the current configuration options available for the `camel-rabbitmq-source-kafka-connector`, the queue and exchange is set to auto-delete by default. If the Kafka connector gets disconnected, then the queue/exchange is deleted, along with any messages on the queue and this would lead to data loss. Being able to define the type and features of the exchange/queue would really improve this connector. If this is something you think can be done at the Kamelet level, I could go through and add those options.

Thanks again for your help and guidance
