### ISSUE TITLE
CamelJiraSinkConnector error - A valid project key is required.

### ISSUE THREAD

**Issue by aggever** [apache/camel-kafka-connector#1467]
Hello,

I am trying the Jira source and sink Connectors (version 0.11.5.). The source connector pulls new issues nicely, but the sink connector complains about the project key missing:

```
org.apache.kafka.connect.errors.ConnectException: Exchange delivery has failed!
...
Caused by: java.lang.IllegalArgumentException: A valid project key is required.
        at org.apache.camel.component.jira.producer.AddIssueProducer.process(AddIssueProducer.java:75)
```

Looking at the [docs](https://camel.apache.org/components/3.18.x/jira-component.html#_message_headers), it seems I have to set the [ISSUE_PROJECT_KEY](https://javadoc.io/doc/org.apache.camel/camel-jira/latest/org/apache/camel/component/jira/JiraConstants.html#ISSUE_PROJECT_KEY) header, but I cannot find how to do that in the sink connector properties.

Assuming that I am correct in the above, my question is:
* How do I define the Jira project key in the sink connector properties?
* What is the reason for having to define the Jira project key as a header and not as a property?

Many thanks!

**Comment by oscerd** [comment]
This is outdated, you need to specify ce-issueKey header.
