### ISSUE TITLE
camel-kafka-connector-generator-maven-plugin: implement a component exclusion mechanism

### ISSUE THREAD

**Issue by valdar** [apache/camel-kafka-connector#148]
See: https://github.com/apache/camel-kafka-connector/blob/master/tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/GenerateCamelKafkaConnectorsMojo.java#L103

**Comment by oscerd** [comment]
Filter must stay
