### ISSUE TITLE
camel-kafka-connector-generator-maven-plugin: optionally delete submodules not in catalog

### ISSUE THREAD

**Issue by valdar** [apache/camel-kafka-connector#149]
This needs an exclusion mechanism as well.

See: https://github.com/apache/camel-kafka-connector/blob/master/tooling/camel-kafka-connector-generator-maven-plugin/src/main/java/org/apache/camel/kafkaconnector/maven/GenerateCamelKafkaConnectorsMojo.java#L170

**Comment by svkcemk** [comment]
@valdar I wanted to work on this one, I am just starting with camel-kafka-connector would be a good starting point for me !

**Comment by KishaKandha** [comment]
Hi @valdar , may I take this task?

**Comment by KishaKandha** [comment]
Hi @valdar , Do I  need  the basic **camel** knowledge to use the camel-kafka-connector?

**Comment by valdar** [comment]
To use them, probably not. To contribute to it most probably you do.

**Comment by KishaKandha** [comment]
Hi @valdar , I would like to request your guidance to resolve this issue. I  just start with reading  camel docs to  get the basic   camel knowledge to use the camel-kafka-connector.Thanks.

**Comment by claudio4j** [comment]
@valdar just to confirm my understanding about this feature, if a given camel component such as `box` is not present in camel catalog, the corresponding `camel-box-kafka-connector` directory should be removed ? Of course there should be a new parameter to control this behavior.

**Comment by valdar** [comment]
Correct, one should also remove the corresponding module in the pom module list.

**Comment by claudio4j** [comment]
@valdar can you close this issue ? Thanks.
