### ISSUE TITLE
Find a way to manage dependencies

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#15]
In order to support camel components, the proper dependencies must be in the classpath. Decide a way to do it, there are some alternatives:

- trivial option: put all the supported camel components as project dependencies
- generate a kafka connector for each component like more or less is done for camel spring boot starters

comment 1 by @oscerd: Maybe the second one and then release a bom with all the kafka-connector we have.

comment 2 by @omarsmak: @valdar @oscerd question wondering in my head, I think there are components IMHO don't make sense to be contained as Kafka Connect connector (e.g: activemq, osgi related ..etc), how do we plan to tackle these?

**Comment by valdar** [comment]
Thanks to https://github.com/apache/camel-kafka-connector/pull/102 we have in place the structure and dependency generation of a Kafka connector for each component.

The missing bits, apart from polishing and inevitable issues, is to generate the 4 classes needed for each connector to configure and work properly.
