### ISSUE TITLE
amqps issue

### ISSUE THREAD

**Issue by Alexander-ac** [apache/camel-kafka-connector#1511]
Hi, 
I tried using amqps. No matter what I do, I'm unsuccessful. 

I use the following components:
camel-jms-amqp-10-source-kafka-connector-3.18.2-package.tar.gz
apache-qpid-jms-0.55.0-bin.tar.gz

My configuration file looks like this:

name=CamelAmqpSourceConnector
tasks.max=1
connector.class=org.apache.camel.kafkaconnector.jmsamqp10source.CamelJmsamqp10sourceSourceConnector
camel.kamelet.jms-amqp-10-source.remoteURI=amqps://xxxxxxx.amazonaws.com:5671
camel.kamelet.jms-amqp-10-source.username=admin
camel.kamelet.jms-amqp-10-source.password=secret
camel.kamelet.jms-amqp-10-source.destinationType=queue
camel.kamelet.jms-amqp-10-source.destinationName=SourceConnector
topics=TEST_TOPIC
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter

Can anyone tell me what I am doing wrong?

**The following error occurs:**

 Could not refresh JMS Connection for destination 'Input.SourceConnector' - retrying using FixedBackOff{interval=5000, currentAttempts=1, maxAttempts=unlimited}. Cause: Client failed to authenticate using SASL: ANONYMOUS (org.apache.camel.component.jms.DefaultJmsMessageListenerContainer:1007)

**Comment by orpiske** [comment]
So, it failed to authenticate, but there should be a reason as to why that happened. If you can, increase the log level and provide the files (or at, least, a full stack trace).

**Comment by Alexander-ac** [comment]
Somehow I have the strong suspicion that the username and password have to be set elsewhere. I don't know how though.

**Comment by Alexander-ac** [comment]
I found the problem. However, the problem was different and the port was actually not activated in the firewall. 
The error message is definitely misleading at this point. 
The settings are correct. So I will close the ticket.
