### ISSUE TITLE
Transformer not printing the custom headers set in Processor

### ISSUE THREAD

**Issue by amulrajesh** [apache/camel-kafka-connector#1520]
Using kafka-connector and kamelets,

I am setting some custom header in Processor,

```
public class CustomProcessor implements Processor {
  @Override
  public void process(Exchange exchange) throws Exception {
      exchange.getMessage().setHeader("dummy", "dummy");
      exchange.getIn().setHeader("dummy", "dummy");
 }
}
```
And I am trying to get the header value (from above step) in Transformer,
```
public class CamelToKafkaHeadersTransform<R extends ConnectRecord<R>> implements
    Transformation<R> {
  @Override
  public R apply(R record) {
      for(Header header : record.headers()) {
            System.out.println(header.key(), header.value());
      }
  }
}
```

Except the custom header I am able to print other camel header values.

**Comment by squakez** [comment]
@amulrajesh I've moved the issue in the camel-kafka-connector project where I think you'll receive better support.

**Comment by oscerd** [comment]
It needs to be prefixed with CamelHeader.

As reported in the documentation and in the code: https://github.com/apache/camel-kafka-connector/blob/07013f7e84b6516103479fcb20537688d461ea4d/core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkTask.java#L48

essentially it needs to CamelHeader.dummy as header name.
