### ISSUE TITLE
[Question] Can I use connectors with Kafka 2.8.1 on Amazon MSK?

### ISSUE THREAD

**Issue by jaehyeon-kim** [apache/camel-kafka-connector#1525]
Hello,

I saw the latest LTS connectors depend on Apache Kafka at version 2.8.0. I plan to test some of them on Amazon MSK and the recommended version is 2.8.1.

Can I use the connectors with the recommended version?

Cheers,
Jaehyeon

**Comment by jaehyeon-kim** [comment]
I see compatibility matrix up to version 1.0.0 - https://github.com/apache/camel-kafka-connector/blob/camel-kafka-connector-1.0.0/docs/modules/ROOT/pages/user-guide/camel-compatibility-matrix.adoc. It indicates Kafka 2.8.0, but it is deleted for later versions.

**Comment by davsclaus** [comment]
Yes Camel Kafka Connectors are using the Kafka Client which often is compatible with different broker versions, especially when the two versions are closer, eg 2.8.0 and 2.8.1.

**Comment by jaehyeon-kim** [comment]
Thank you so much @davsclaus!
