### ISSUE TITLE
syslog connector failure

### ISSUE THREAD

**Issue by brian-keplinger** [apache/camel-kafka-connector#1528]
I may be doing something wrong but several of us have spent many hours trying to figure this out. Any assistance would be greatly appreciated. 

[2023-05-05 01:20:38,082] ERROR Failed to create job for /opt/kafka_2.13-2.8.1/config/CamelSyslogSourceConnector.properties (org.apache.kafka.connect.cli.ConnectStandalone:107)
[2023-05-05 01:20:38,082] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:117)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches org.apache.camel.kafkaconnector.syslog.CamelSyslogSourceConnector

CamelSyslogSourceConnector.properties
##
##
## ---------------------------------------------------------------------------

name=CamelSyslogSourceConnector
connector.class=org.apache.camel.kafkaconnector.syslog.CamelSyslogSourceConnector
tasks.max=1

# use the kafka converters that better suit your needs, these are just defaults:
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter

# comma separated topics to send messages into
topics=syslog

# mandatory properties (for a complete properties list see the connector documentation):

# The protocol to use which can be tcp or udp. One of: [tcp] [udp]
camel.source.path.protocol=udp
# The hostname. For the consumer the hostname is localhost or 0.0.0.0. For the producer the hostname is the remote host to connect to
camel.source.path.host=0.0.0.0
# The host port number
camel.source.path.port=514

**Comment by brian-keplinger** [comment]
answer use fluentd so much simpler.

**Comment by oscerd** [comment]
It seems you passed to something else. No answers.
