### ISSUE TITLE
Delete file in ftp after processed

### ISSUE THREAD

**Issue by LinzeSu** [apache/camel-kafka-connector#1535]
Hi all,

I'd like for some help on the configuration of the sftp connector. Basically I'm reading files from sftp server and forward it to kafka, and I want the files to be deleted after this process. In [CAMEL-SFTP-SOURCE-KAFKA-CONNECTOR SOURCE CONFIGURATION](https://camel.apache.org/camel-kafka-connector/3.18.x/reference/connectors/camel-sftp-source-kafka-source-connector.html) there's no such setting. And in an [example provided with version 0.11.5](https://github.com/apache/camel-kafka-connector-examples/tree/main/sftp/sftp-source), there's similar settings that goes:
```
camel.source.endpoint.noop=false
camel.source.endpoint.move=.done
```
and the settings are still provided in [CAMEL-FILE-KAFKA-CONNECTOR SOURCE CONFIGURATION](https://camel.apache.org/camel-kafka-connector/3.18.x/reference/connectors/camel-file-kafka-source-connector.html). I set `camel.source.endpoint.delete` to `true` but it does not really work. I assume that the file source connetor is a more generic way and probably is the underlying layer of the ftp connector, and there should be some way that I could pass the config and make it work. Suggestions are appreciated.

**Comment by oscerd** [comment]
What version of the connector are you using?

**Comment by LinzeSu** [comment]
> What version of the connector are you using?

Thanks for the lightning fast reply. I'm using version 3.20.3.

**Comment by LinzeSu** [comment]
Thanks. This feature is greatly in need cause when the number of files in the dir the connector reads exceeds 1000, the connector will repeatedly read the files, which I assume is an unwanted situation. I just came across this problem when doing connector upgrade and I found the info [here](https://camel.apache.org/components/next/file-component.html):
```
Option to use the Idempotent Consumer EIP pattern to let Camel skip already processed files. 
Will by default use a memory based LRUCache that holds 1000 entries. 
```
Please let me know if this feature is added in the future release.

**Comment by oscerd** [comment]
idempotent is already enabled in the connector, so you shouldn't consume the same files multiple times. It should work, but it won't delete the files.

**Comment by LinzeSu** [comment]
Yeah, I know it's enabled by default and I even set it to true just to avoid misunderstanding. Still the connectors won't stop sending same file record to kafka.
According to the documentation the connector only holds the latest 1000 names of the file it processed. So newly processed filename will replace the name in that LRUCache. 
Also, is there any specifc version that could be used to avoid this? Maybe a version that's not based on Kamelets?

**Comment by oscerd** [comment]
No, there is no specific version.

**Comment by oscerd** [comment]
This has been add here: https://github.com/apache/camel-kamelets/issues/1507

And it will be in 3.20.6

**Comment by LinzeSu** [comment]
That's great. Thanks oscerd.
