### ISSUE TITLE
[Question] Amazon Opensearch Compatibility?

### ISSUE THREAD

**Issue by jaehyeon-kim** [apache/camel-kafka-connector#1546]
Hello,

Just a quick question if the following Kafka connectors may be used for Amazon Opensearch.

* camel-elasticsearch-index-sink-kafka-connector
* camel-elasticsearch-search-source-kafka-connector

**Comment by oscerd** [comment]
No, it's not supposed to work with that. But you can try. We never tried with opensearch

**Comment by jaehyeon-kim** [comment]
@oscerd 

Thanks for your answer. I'm new to ElasticSearch/OpenSearch and wouldn't be able to handle an issue that may occur when I try those connectors with OpenSearch. I'd try it later when I get some more experience.

Cheers,
Jaehyeon
