### ISSUE TITLE
CAMEL-AZURE-SERVICEBUS-SOURCE-KAFKA-CONNECTOR

### ISSUE THREAD

**Issue by itwolf81** [apache/camel-kafka-connector#1547]
Azure ServiceBus connector doesn't allow me to configure if topicOrQueueName is topic or queue. Therefor if I provide topic with subscriptionName connector failes on error:
`[kafka-artemis-azure-servicebus-connector|task-0] Error processing exchange. Exchange[]. Caused by: [com.azure.messaging.servicebus.ServiceBusException - The messaging entity 'internal-support-artemis-dev:Topic:sync_events_from_artemis|sync_events_from_artemis_3cab19_1691337361723' could not be found.`

Please add support to configure also camel.kamelet.azure-servicebus-source.serviceBusType (topic / queue).

**Comment by itwolf81** [comment]
> Azure ServiceBus connector doesn't allow me to configure if topicOrQueueName is topic or queue. Therefor if I provide topic with subscriptionName connector failes on error: `[kafka-artemis-azure-servicebus-connector|task-0] Error processing exchange. Exchange[]. Caused by: [com.azure.messaging.servicebus.ServiceBusException - The messaging entity 'internal-support-artemis-dev:Topic:sync_events_from_artemis|sync_events_from_artemis_3cab19_1691337361723' could not be found.`
> 
> Please add support to configure also camel.kamelet.azure-servicebus-source.serviceBusType (topic / queue).

I investigated further, while I'm new to this project and looks like first thing is to add this config value to the kamelet project. Could you please navigate me somewhere, how to setup whole camel + kamelet + camel-kafka-connector solution localy so I can maybe fix this by myself and add a pull request afterwards? Thanks.

**Comment by oscerd** [comment]
https://github.com/apache/camel-kamelets/blob/main/kamelets/azure-servicebus-source.kamelet.yaml

https://github.com/apache/camel-kamelets/blob/main/kamelets/azure-servicebus-sink.kamelet.yaml
