### ISSUE TITLE
SNS Sink Connector failure - java.lang.NoClassDefFoundError: software/amazon/awssdk/utils/cache/CachedSupplier$StaleValueBehavior

### ISSUE THREAD

**Issue by mohit-chopra** [apache/camel-kafka-connector#1548]
We are getting `java.lang.NoClassDefFoundError: software/amazon/awssdk/utils/cache/CachedSupplier$StaleValueBehavior`with camel-aws-sns-sink-kafka-connector-3.18.2.

This error is resolved when aws sdk utils-2.17.250.jar is used instead of `utils-2.17.223` shipped with connector.

Configuration for connector:

```
"camel.kamelet.aws-sns-sink.topicNameOrArn" : "topic-arn",  
"camel.kamelet.aws-sns-sink.region": "aws-reg",
"camel.kamelet.aws-sns-sink.useDefaultCredentialsProvider": true
```

Is there a patch/fix lined up to address this issue?

**Comment by oscerd** [comment]
It should be fixed in 3.20.x
