### ISSUE TITLE
issue in CAMEL-SALESFORCE-UPDATE-SINK-KAFKA-CONNECTOR  properties 

### ISSUE THREAD

**Issue by Ziauddin135** [apache/camel-kafka-connector#1558]
we are trying to use CAMEL-SALESFORCE-UPDATE-SINK-KAFKA-CONNECTOR for our use case but found something inflexible in the connector config properties

Property  **camel.kamelet.salesforce-update-sink.clientId = Required The ID of the Salesforce object. Required if using a key-value pair. Its Id value like "1222455353"**

This required property in camel connector configuration makes this connector only work for a particular record sObjectId of sObject. that means if we have 1 million records, we need to have those many connectors running.

**Comment by oscerd** [comment]
This has been change in camel-kamelets 4.x and will be part of Ckc 4: https://github.com/apache/camel-kamelets/blob/main/kamelets/salesforce-update-sink.kamelet.yaml

**Comment by Ziauddin135** [comment]
Hi @oscerd ,
Thank you for you response. could you please help to know when ckc 4 going to be released?
as we see here https://repo1.maven.org/maven2/org/apache/camel/kafkaconnector/ CKC version 3.20.6 is released . when can we expect CKC 4 or CKC 3.21.0 version?

Thank you :)

**Comment by oscerd** [comment]
CKC 3.21.0 will be released this week. It's on vote. 4.0 should be the next week, but we have some issues to complete before.
