### ISSUE TITLE
How to create an object in s3 bucket using camle-minio-sink plugin

### ISSUE THREAD

**Issue by shubhamcoc** [apache/camel-kafka-connector#1560]
Hi, 
I am trying to take backup of multiple Kafka topics data in s3 bucket, current observation is, minio-sink plugin is creating random file in same bucket without storing the metadata, as a result, during the restore all the data saved into bucket will be restore in all the topics. 

I can see in the [kamalet yaml](https://github.com/apache/camel-kafka-connector/blob/main/connectors/camel-minio-sink-kafka-connector/src/main/resources/kamelets/minio-sink.kamelet.yaml), it is mention, we have to set header properties called file to upload the data into the filename. Do anyone know how to configure it? 

I find one property to set the keyname in endpoint, but it is not working as intended. There is a similar question in stack-overflow https://stackoverflow.com/questions/74662272/kafka-connect-camel-s3-sink-keyname-attribute-behavior. 

Any help is appreciated. Thanks in advance. Kindly let me know if it is possible to store data into a particular object in a bucket.

**Comment by shubhamcoc** [comment]
Thanks @oscerd for the response, I think it will be helpful if you add it in the documentation as well. I will try it out and will ask again if we face some issue.

**Comment by shubhamcoc** [comment]
Hi @oscerd, I tried to send the data using kafkacat with header, as suggested in above comment, but it is still uploading data using exchange ID. Do we need to configure anything related to header configurations?

**Comment by oscerd** [comment]
How are you sending the data?

**Comment by shubhamcoc** [comment]
using the command 
```
kcat -P -b localhost:9092 -X security.protocol=SSL -X ssl.key.location=/ssl/certsClient/tls.key -X ssl.certificate.location=/ssl/certsClient/tls.crt -X ssl.ca.location=/ssl/certsCl
ient/ca.crt -t kafkatopic-sample -H "CamelHeader.CamelMinioObjectName=kafkatopic-sample-test"
```

**Comment by oscerd** [comment]
> using the command
> 
> ```
> kcat -P -b localhost:9092 -X security.protocol=SSL -X ssl.key.location=/ssl/certsClient/tls.key -X ssl.certificate.location=/ssl/certsClient/tls.crt -X ssl.ca.location=/ssl/certsCl
> ient/ca.crt -t kafkatopic-sample -H "CamelHeader.CamelMinioObjectName=kafkatopic-sample-test"
> ```

My bad the correct header name is file

So it should be

```
kcat -P -b localhost:9092 -X security.protocol=SSL -X ssl.key.location=/ssl/certsClient/tls.key -X ssl.certificate.location=/ssl/certsClient/tls.crt -X ssl.ca.location=/ssl/certsClient/ca.crt -t kafkatopic-sample -H "CamelHeader.file=kafkatopic-sample-test"
```

**Comment by shubhamcoc** [comment]
Thanks, this time, it worked, another question is, whenever we send a msg, the file gets overwrite, is there any way to append the messages?

**Comment by shubhamcoc** [comment]
What do you mean by plain camel? can we connect to s3 using plain camel without plugins?

**Comment by oscerd** [comment]
I mean using Apache Camel without kafka connect. https://camel.apache.org/camel-core/

**Comment by oscerd** [comment]
Or you can try the aggregation in CKC: https://camel.apache.org/camel-kafka-connector/3.18.x/user-guide/aggregation.html

**Comment by oscerd** [comment]
> What do you mean by plain camel? can we connect to s3 using plain camel without plugins?

For sure you can. https://camel.apache.org/components/4.0.x/aws2-s3-component.html

**Comment by shubhamcoc** [comment]
> Or you can try the aggregation in CKC: https://camel.apache.org/camel-kafka-connector/3.18.x/user-guide/aggregation.html

ok I will check the aggregation first, if it helps then fine or else will check camel-core component. Thanks a lot.

**Comment by shubhamcoc** [comment]
> > What do you mean by plain camel? can we connect to s3 using plain camel without plugins?
> 
> For sure you can. https://camel.apache.org/components/4.0.x/aws2-s3-component.html

This is for aws S3, unfortunately ours is not hosted on AWS, and I am not sure if it is generic for all S3 storage.

**Comment by shubhamcoc** [comment]
Thanks, closing the ticket as the solution is working.
