### ISSUE TITLE
GroupID for HTTP sink

### ISSUE THREAD

**Issue by giulio1979** [apache/camel-kafka-connector#1574]
Is there a way to set kafka source groupid ? I am having problems setting groupId according to Kafka user policy

I am using Kafka HTTP Sink connector.

org.apache.kafka.common.errors.GroupAuthorizationException: Not authorized to access group: connect-http-post-kafka-http-connector

**Comment by oscerd** [comment]
What version of camel-kafka-connector are you using? Can you please show your configuration for HTTP sink connector?

**Comment by giulio1979** [comment]
I tried to sanitize a bit but roughly this is it:

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    app.kubernetes.io/instance: http-post
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka-http-connector
    strimzi.io/cluster: httpconnect-kafka-connect-cluster
  name: http-post-kafka-http-connector
  namespace: test
spec:
  class: org.apache.camel.kafkaconnector.httpsink.CamelHttpsinkSinkConnector
  config:
    camel.kamelet.http-sink.method: POST
    camel.kamelet.http-sink.url: https://simpletest.requestcatcher.com/
    errors.tolerance: all
    group.id: sometest
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://schema-registry.shared-services.svc.cluster.local:8081
    key.converter.schemas.enable: 'true'
    output.data.format: JSON
    topics: sometest.chuck-norris
    transforms: tojson
    transforms.tojson.converter.type: value
    transforms.tojson.type: org.apache.camel.kafkaconnector.transforms.SchemaAndStructToJsonTransform
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://schema-registry.shared-services.svc.cluster.local:8081
    value.converter.schemas.enable: 'true'
  tasksMax: 1

**Comment by oscerd** [comment]
@valdar

**Comment by giulio1979** [comment]
I ended up changing the access policy for the user to match the group name pattern connect-<connector name>*.

Not sure if this is intended.
