### ISSUE TITLE
[4.0.0] Missing RabbitMQ Source Connector

### ISSUE THREAD

**Issue by dshma** [apache/camel-kafka-connector#1576]
Hello there,

I've come across the following in [the other ticket](https://github.com/apache/camel-kamelets/issues/1228#issuecomment-1449392868):

> Rabbitmq has been deprecated and removed in camel 4. So we're going to use spring-rabbitmq component in main.

I see there is no RabbitMQ Component since Camel 4.0.x and the Spring RabbitMQ Component has been supported since Camel 3.8. However, since the new Camel Kafka Connector implementation uses Kamelets, we'd need the Spring RabbitMQ Kamelet, which hasn't been released as part of the Kamelet Catalog 4.0.x and is still omitted in the Next (Pre-release) version, which appears to be 4.1.x. As a result, the Next (Pre-release) version of the Camel Kafka Connect (4.0.x), which in turn depends on Kamelets 4.0.0, won't have support for RabbitMQ at all if I understand correctly, hence requesting support for it (or to hear back from you on this). RabbitMQ seems like a quite typical use case one might need.

Also, from what I behold there is no SSL/TLS support since Kamelets came out, is there an explanation for this? This made us use the old implementation of the Camel Kafka Connector as the RabbitMQ Component did support SSL configs.

Thanks in advance for your time.

**Comment by oscerd** [comment]
This is done from a while
