### ISSUE TITLE
Camel components secret options are showed in logs

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#159]
If you set an option like for example an AWS secret key in one of the connector configuration it will be showed up in the log in clear.

**Comment by valdar** [comment]
Do we have some facility at Camel level to deal with this? I suspect that we must search for such an option in Kafka connect framework.

**Comment by davsclaus** [comment]
Yeah see how we do something like that in camel-main or the santize uri method

org.apache.camel.util.URISupport#sanitizeUri
org.apache.camel.main.BaseMainSupport#SENSITIVE_KEYS

**Comment by oscerd** [comment]
Should be ok now.

**Comment by oscerd** [comment]
Let's keep it open until we update master to 3.8.0

**Comment by oscerd** [comment]
Done
