### ISSUE TITLE
Kafka Events batching 

### ISSUE THREAD

**Issue by AishD3** [apache/camel-kafka-connector#1605]
Hi @oscerd , we would like batch some amount of kafka records while a file is created in data lake . We are using below configs in Kafka Connect for that , but batching is not working , is it correct and am I missing something. 

    camel.aggregation.size: 5
    camel.aggregation.timeout: 5000

**Comment by oscerd** [comment]
https://camel.apache.org/camel-kafka-connector/4.0.x/user-guide/aggregation.html

**Comment by AishD3** [comment]
@oscerd Yes we referred to this , but do we need to add camel.beans.aggregate=#class:org.apache.camel.kafkaconnector.aggregator.StringAggregator 

as well , or only 

camel.aggregation.size: 5
camel.aggregation.timeout: 5000

is enough

**Comment by oscerd** [comment]
You need to add a bean because otherwise Camel don't know how to aggregate.

**Comment by AishD3** [comment]
Thanks a lot its working

**Comment by skumaravelan** [comment]
Can you share the dsl

**Comment by skumaravelan** [comment]
@AishD3 , could you share the dsl and how so use this aggregator
