### ISSUE TITLE
Directory name for Azure Datalake Kafka sink Connector

### ISSUE THREAD

**Issue by AishD3** [apache/camel-kafka-connector#1606]
Hi @oscerd , Sorry to pour questions to you , This is the last one I am asking you , Right now fileName is working fine if we pass from kafkaheaders, How can move certain files to certain directory in run time, is it only 

    camel.kamelet.azure-storage-datalake-sink.fileSystemName: test

Or is it something else as well that we can use.

**Comment by AishD3** [comment]
CamelHeader.CamelAzureStorageDataLakeDirectoryName this I need to pass is Kafka Header again ?

**Comment by oscerd** [comment]
yes.
