### ISSUE TITLE
Produce a download/release page

### ISSUE THREAD

**Issue by valdar** [apache/camel-kafka-connector#163]
Produce a release page on the line of https://camel.apache.org/download/ part is manually created, a part is generated.

**Comment by oscerd** [comment]
@zregvart can you help on this?

**Comment by zregvart** [comment]
There's documentation on how to [create a release note](https://github.com/apache/camel-website/#adding-new-release-note). The layout for the downloads page is [here](https://github.com/apache/camel-website/blob/master/layouts/download/download.html).

**Comment by oscerd** [comment]
Yes, but that seems to be for camel only

**Comment by zregvart** [comment]
A release note can be done for sub-projects and the layout can be extended to include those as separate entities. For example we currently filter on `rc` parameter indicating a release candidate, `project` parameter can be added to filter by projects.
