### ISSUE TITLE
CKC 4.4.3 release

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-kafka-connector#1656]
Upgrade to Camel 4.4.3 and do a new release

**Comment by davsclaus** [comment]
@oscerd we would need a kamelets 4.4.3 release

**Comment by oscerd** [comment]
I'll release on Monday

**Comment by davsclaus** [comment]
@valdar okay so we have upgraded to 4.4.3 and a release is welcome

**Comment by davsclaus** [comment]
Did we find time to cut a CKC release

**Comment by valdar** [comment]
The vote is open.

**Comment by valdar** [comment]
Released.
