### ISSUE TITLE
Add tests to camel-kafka-connector-generator-maven-plugin

### ISSUE THREAD

**Issue by valdar** [apache/camel-kafka-connector#166]
Using some maven plugin test project add tests to https://github.com/apache/camel-kafka-connector/tree/master/tooling/camel-kafka-connector-generator-maven-plugin

**Comment by tadayosi** [comment]
There are very few options of testing framework that can be used with JUnit 5.
https://khmarbaise.github.io/maven-it-extension/itf-documentation/background/background.html
I initially tried to use [maven-plugin-testing-harness](https://maven.apache.org/plugin-testing/maven-plugin-testing-harness/getting-started/index.html) but it only supports up to JUnit 4. Fitting it into JUnit 5 is hard and should easily become hacky.

So far the most popular and promising framework seems to be [khmarbaise/maven-it-extension](https://github.com/khmarbaise/maven-it-extension), which supports JUnit 5 and is being actively developed, so I'm going to write some tests with the framework.

@valdar @oscerd @orpiske WDYT?  Do you have any opinions about the choice of the testing frameworks?

**Comment by oscerd** [comment]
I think maven-it-extension is the right choice to be in sync with the junit 5 usage, thanks for looking into this.

**Comment by orpiske** [comment]
+ for maven-it-extension and keeping in sync w/ JUnit 5. 

On a side note, @tadayosi: there were a recent cleanup of the IT tests that should provide a good starting point for any new test case: the `CamelSinkTestSupport` and the `CamelSourceTestSupport`. These classes generalize the connector's test life cycle and implementations need to basically create the specific producer or consumer for the endpoint.

**Comment by tadayosi** [comment]
Thanks @orpiske for the info. Since it's maven plugin IT tests I don't think we can reuse the same test support for CKC connectors, but I'll check them and try to follow the same styles as much as possible.
