### ISSUE TITLE
how to process data in kafka topic and write an xml file to the SFTP location using camel-kafka-sftp-sink-connector

### ISSUE THREAD

**Issue by hvinjarapu** [apache/camel-kafka-connector#1663]
Need to process data in kafka topic and write an xml file to the SFTP location using camel-kafka-sftp-sink-connector. 
Currently no extension is attached to the file created in SFTP location. 
followed the official doco and sending file name to be used in kafka message header, however that value is not used but exchange id is used as the file name.

**Comment by oscerd** [comment]
This is not an issue it's a request for help, use Zulip or mailing list.
