### ISSUE TITLE
Request CamelHttpsSinkConnector can expose property camel.sink.endpoint.okStatusCodeRange

### ISSUE THREAD

**Issue by KevinMeng4662** [apache/camel-kafka-connector#1675]
hi Team,

In the document https://camel.apache.org/camel-kafka-connector/next/reference/connectors/camel-https-kafka-sink-connector.html mentioned the property "camel.sink.endpoint.okStatusCodeRange" : "The status codes which are considered a success response. The values are inclusive. Multiple ranges can be defined, separated by comma, e.g. 200-204,209,301-304. Each range must be a single number or from-to with the dash included."

But it is not exposed for CamelHttpsSinkConnector 4.4.3
Could you please plan to expose property camel.sink.endpoint.okStatusCodeRange for CamelHttpsSinkConnector.

Thanks

**Comment by oscerd** [comment]
The documentation is pointing to main so it's not up-to-date. We need to publish the correct one.

**Comment by oscerd** [comment]
By the way the correct documentation is this: https://camel.apache.org/camel-kafka-connector/4.4.x/reference/connectors/camel-http-secured-sink-kafka-sink-connector.html. With 4.4.x you're using this Kamelet with HTTPS

**Comment by valdar** [comment]
@KevinMeng4662 the property seems to be exposed https://github.com/apache/camel-kafka-connector/blob/camel-kafka-connector-4.4.3/connectors/camel-https-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/https/CamelHttpsSinkConnectorConfig.java#L78 even for 4.4.3 version.

What errors are you getting and how are you using that connector?
