### ISSUE TITLE
Avoid Thread.sleep in test, use Awaitility FTW

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#186]

**Comment by oscerd** [comment]
It's not really straighforward to do. We need probably to rethink the tests. I'll leave this open.

**Comment by orpiske** [comment]
> It's not really straighforward to do. We need probably to rethink the tests. I'll leave this open.

Is there any particular test you think it's problematic?

**Comment by oscerd** [comment]
The CamelSourceTaskTest in particular, wherever thread.sleep is used.

**Comment by orpiske** [comment]
> The CamelSourceTaskTest in particular, wherever thread.sleep is used.

+1.

There's a few on CamelSourceAWSKinesisITCase too. Although they are still using an approach similar to the one [suggest by amazon](https://docs.aws.amazon.com/general/latest/gr/api-retries.html), I also think they could be improved.

**Comment by fvaleri** [comment]
There is a proposed refactoring of `CamelSourceTaskTest` here:
https://github.com/apache/camel-kafka-connector/pull/201

I'm not using Awaitility, but a shared method called `getTaskWithFixedNumberOfRecords`. All properties from `CamelSourceConnectorConfig` used inside it are tested in isolated methods, so I think it's fine to use them when testing source task behaviors that do not involve them.

**Comment by valdar** [comment]
I preferred to get rid of sleep(...) as in #204. From a long run on my machine, they seem stable enough now.

@fvaleri @orpiske @oscerd feel free to improve it in any way you see fit.
