### ISSUE TITLE
Improve integration test support when component dependencies are present

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#211]
In a scenario where you are testing Camel component A and your test depends on Camel component B is necessary to include Camel component B as a provided dependency on the test pom. 

This makes testing more complicated, pollutes the pom and makes it harder to manage test dependencies.

**Comment by orpiske** [comment]
Based on a discussion with @valdar

**Comment by valdar** [comment]
It is mildly related to #191

**Comment by valdar** [comment]
Easy and useful mitigation would be to have each connector tests under a submodule of the `tests` project, so one can better control the tests classpath by having only the dependencies needed by a specific connector.

**Comment by orpiske** [comment]
> Easy and useful mitigation would be to have each connector tests under a submodule of the `tests` project, so one can better control the tests classpath by having only the dependencies needed by a specific connector.

+1. I think it would also make it easier to look at the tests logs. Right now, if we run all the tests at once, we end up with large log which is not always easy to read.

**Comment by orpiske** [comment]
@valdar @oscerd I think we can close this since we split the tests in modules. What do you think?
