### ISSUE TITLE
Camel-MongoDB Kafka connector: example with sink connector

### ISSUE THREAD

**Issue by abouchama** [apache/camel-kafka-connector#212]
Is it possible to have an example with sink connector (e.g; CamelMongodbSinkConnector) ?

**Comment by orpiske** [comment]
For the record: I have a TC in progress for this, but there are some things I need to clarify w/ @valdar and @oscerd before sending a PR. Apparently, there's some things that the code needs to to do to have Camel correctly instantiate the connection bean.

**Comment by oscerd** [comment]
This should be done https://github.com/apache/camel-kafka-connector/pull/295/commits/3db491eccbfb6eb2db27e4f4c2e97cf3f0c549e3
