### ISSUE TITLE
Possible problems in CamelSinkAWSSQSITCase tests

### ISSUE THREAD

**Issue by valdar** [apache/camel-kafka-connector#215]
While refactoring tests to accommodate syslog test I properly implemented the `initializeConnectorBlocking` function and started to have random failures from `CamelSinkAWSSQSITCase`. For the moment I changed it to use `initializeConnector`.

Logically there should be no differences in the test outcome using one method or the other, but in case of `initializeConnectorBlocking` there is.

**Comment by valdar** [comment]
cc: @orpiske

**Comment by orpiske** [comment]
@valdar thanks, I'll look into this one.
