### ISSUE TITLE
Integrations tests fails if confluentinc/cp-kafka:5.2.1 has not been pulled

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#25]
if one do a `mvn clean verify package` without having pulled `confluentinc/cp-kafka:5.2.1` this is the result:

```bash
[INFO] Running org.apache.camel.kafkaconnector.source.timer.CamelSourceTimerITCase
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.141 s <<< FAILURE! - in org.apache.camel.kafkaconnector.source.timer.CamelSourceTimerITCase
[ERROR] testLaunchConnector(org.apache.camel.kafkaconnector.source.timer.CamelSourceTimerITCase)  Time elapsed: 0.14 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: java.lang.reflect.UndeclaredThrowableException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: com.github.dockerjava.api.exception.NotFoundException: 
{"message":"No such image: confluentinc/cp-kafka:5.2.1"}


[INFO] Running org.apache.camel.kafkaconnector.sink.jms.CamelSinkJMSITCase
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.155 s <<< FAILURE! - in org.apache.camel.kafkaconnector.sink.jms.CamelSinkJMSITCase
[ERROR] testBasicSendReceive(org.apache.camel.kafkaconnector.sink.jms.CamelSinkJMSITCase)  Time elapsed: 0.155 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: java.lang.reflect.UndeclaredThrowableException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: com.github.dockerjava.api.exception.NotFoundException: 
{"message":"No such image: confluentinc/cp-kafka:5.2.1"}
```
author @valdar 

comment 1 by @valdar : @orpiske can you take a look?

comment 2 by @orpiske : @valdar absolutely. I will take a look at this one.

comment 3 by @orpiske : @valdar is there any more details you could share about your environment? I haven't been able to reproduce it yet. I have tried a couple of things* - always using a clean environment - but none worked so far (different docker versions, OSes (Fedora/RHEL), System configurations, etc).

comment 4 by @valdar : @orpiske sure:

```bash
$ cat /etc/fedora-release 
Fedora release 30 (Thirty)
```
```bash
$ docker --version
Docker version 19.03.2, build 6a30dfc
```
no particular configs that I am aware might affect this issue

comment 5 by @orpiske : Thanks @valdar. When you get a chance, can you also attach the tests.log for when this issue happen, please? I have a guess that this might be related to an unreliable or slow network and I think I can get some clues from that from that log.

**Comment by valdar** [comment]
[tests.log](https://github.com/apache/camel-kafka-connector/files/3952581/tests.log) here it is @orpiske

**Comment by valdar** [comment]
it seems that the problem was somehow related to my docker environment being tainted somehow. Starting from a fresh docker environment (i.e. by stopping docker deamon, forcefully removing `/var/lib/docker` directory and starting the docker deamon again) the error diappeared. 
Here are the images pulled as a result of a fresh `mvn clean install`:
```$ docker images
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
centos                                              8                   0f3e07c0138f        2 months ago        220MB
docker.elastic.co/elasticsearch/elasticsearch-oss   7.3.2               876f2f753cc8        3 months ago        612MB
localstack/localstack                               0.9.4               5c6c5a293024        6 months ago        1.29GB
confluentinc/cp-kafka                               5.2.1               af7cf4356c58        8 months ago        569MB
quay.io/testcontainers/ryuk                         0.2.3               64849fd2d464        10 months ago       10.7MB
alpine                                              3.5                 f80194ae2e0c        10 months ago       4MB
```

@orpiske I don't remember if you were working on removing the need for `confluentinc/cp-kafka` replacing it with some upstream alternative?

**Comment by orpiske** [comment]
> It seems that the problem was somehow related to my docker environment being tainted somehow.
> 
> Starting from a fresh docker environment (i.e. by stopping docker deamon, forcefully removing `/var/lib/docker` directory and starting the docker deamon again) the error disappeared.

Hey, this is great. I couldn't find much by looking at the logs, but I found some occurrences about this issue on the internet and on a few of them people were claiming that the issue would go away with a ```docker system prune```. I was a bit skeptical as you did not seem to have problems outside the test suite, but apparently it may have some effect after all. 

> 
> Here are the images pulled as a result of a fresh `mvn clean install`:
> 
> ```
> REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
> centos                                              8                   0f3e07c0138f        2 months ago        220MB
> docker.elastic.co/elasticsearch/elasticsearch-oss   7.3.2               876f2f753cc8        3 months ago        612MB
> localstack/localstack                               0.9.4               5c6c5a293024        6 months ago        1.29GB
> confluentinc/cp-kafka                               5.2.1               af7cf4356c58        8 months ago        569MB
> quay.io/testcontainers/ryuk                         0.2.3               64849fd2d464        10 months ago       10.7MB
> alpine                                              3.5                 f80194ae2e0c        10 months ago       4MB
> ```
> 
That looks good! That's what I have here :) 

> @orpiske I don't remember if you were working on removing the need for `confluentinc/cp-kafka` replacing it with some upstream alternative?

Yes I am. I needed to get some patches out of the way first (like #29 and #42) - and then focus on this issue - and now I am going to work on this.

**Comment by valdar** [comment]
Great! So I think we can close this issue and ope another one just to remove the useage of `confluentinc/cp-kafka`.
