### ISSUE TITLE
Camel HDFS: does not work due to dependencies conflicts

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#263]
It seems that the HDFS Connector cannot be loaded due to conflicts between the dependencies used by the component and the ones available on the connect runtime. 

Without manipulating the classpath, loading the dependencies fail because a dependency carried by either one of them does not seem to contain the getProperties on the Application class (which comes from `javax.ws.rs:javax.ws.rs-api`). Manipulating the classpath to include this library and/or exclude specific dependencies cause the connector to fail to load due to other classpath related issues (ie.: `ClassNotFoundException`).

I'll provide more logs later for this one.

**Comment by valdar** [comment]
As @oscerd suggested I think we must handle this at camel component level and align dependencies there if it makes sense.

**Comment by oscerd** [comment]
I guess we need a JIRA for this, because it won't be easy, especially in Karaf.

**Comment by orpiske** [comment]
> I guess we need a JIRA for this, because it won't be easy, especially in Karaf.

I'll open one there.

**Comment by orpiske** [comment]
Done: https://issues.apache.org/jira/browse/CAMEL-15169

**Comment by orpiske** [comment]
For the integration tests, I managed to work-around this problem with a couple of exclusion hacks: https://github.com/orpiske/camel-kafka-connector/blob/hdfs-test/tests/itests-hdfs/pom.xml#L45 

Nonetheless, the package might still have the problem and only work adequately once we get 3.4.0 with @oscerd patches.

**Comment by oscerd** [comment]
Have you tried with 3.4.0-Snapshot

**Comment by orpiske** [comment]
> Have you tried with 3.4.0-Snapshot?

Not yet, but I will do it soon and report back.

**Comment by orpiske** [comment]
> Have you tried with 3.4.0-Snapshot?

So, I tried with and without the excludes and both failed. In both cases, the problem seems to be caused by:

`Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.component.AttributeContainerMap`.

**Comment by oscerd** [comment]
Updated to 3.4.0 and merged, I see that error, so we need to have a look

**Comment by orpiske** [comment]
> Updated to 3.4.0 and merged, I see that error, so we need to have a look

Should I go ahead and disable them while we investigate?

**Comment by oscerd** [comment]
Maybe disable it for the moment

**Comment by orpiske** [comment]
> Maybe disable it for the moment

I sent a PR that fixes the test execution, so we should be fine with regards to the dependencies conflicts. However I am not entirely sure if HDFS is working on some circumstances (specifically within kubernetes/openshift - I am investigating and I'll open a separate ticket if that's the case).
