### ISSUE TITLE
Add CamelAMQP source and sink example properties

### ISSUE THREAD

**Issue by rgannu** [apache/camel-kafka-connector#264]
I was struggling for a day to determine how to transfer the data from kafka to amqp 1.0 broker end point using the camel-amqp-kafka-connector. At the end I was able to do that with the attached sink configuration. 
Could you please add this as part of the examples directory ? 
Also, please add the corresponding the AMQP source configuration. 

examples/CamelAmqpSinkConnector.properties
```
name=CamelAmqpSinkConnector
topics=mytopic
tasks.max=1
connector.class=org.apache.camel.kafkaconnector.amqp.CamelAmqpSinkConnector

camel.sink.path.destinationType=queue
camel.sink.path.destinationName=test-queue

camel.component.amqp.includeAmqpAnnotations=true
camel.component.amqp.connectionFactory=#class:org.apache.qpid.jms.JmsConnectionFactory
camel.component.amqp.connectionFactory.remoteURI=amqp://localhost:5672
camel.component.amqp.username=admin
camel.component.amqp.password=admin
camel.component.amqp.testConnectionOnStartup=true

```

**Comment by oscerd** [comment]
Thanks a lot, Can you open a Pull Request on https://github.com/apache/camel-kafka-connector-examples ?

**Comment by rgannu** [comment]
Created also a pull request in the camel-kafka-connector-examples: https://github.com/apache/camel-kafka-connector-examples/pull/8

**Comment by oscerd** [comment]
Thanks a lot!
