### ISSUE TITLE
Azure blob sink does not put file in azure

### ISSUE THREAD

**Issue by balasapient** [apache/camel-kafka-connector#270]
I am trying to use the azure blob sink connector to read a kafka topic and put the messages as file in azure blob storage. I am using the following config file and the files are not getting created. 

Please find the trace logs here [connect.log](https://github.com/apache/camel-kafka-connector/files/4765904/connect.log)
```
name=CamelAzure-blobSinkConnector1
connector.class=org.apache.camel.kafkaconnector.azureblob.CamelAzureblobSinkConnector
tasks.max=1

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter


topics=mytopic

camel.sink.endpoint.fileDir=/root/plugins
camel.sink.endpoint.streamWriteSize=20
camel.component.azure-blob.fileDir=/root/plugins
camel.component.azure-blob.streamWriteSize=20
camel.sink.path.containerOrBlobUri=accoutname.blob.core.windows.net/vvp-dev/file.txt
camel.component.azure-blob.credentialsAccountKey=key
camel.component.azure-blob.credentialsAccountName=accoutname
```

**Comment by oscerd** [comment]
@balasapient did you find a fix? Can you please add an example here https://github.com/apache/camel-kafka-connector-examples ?

**Comment by balasapient** [comment]
@oscerd I ended up using CamelAzurestorageblobSinkConnector, I will add an example for it.

**Comment by oscerd** [comment]
@balasapient any news about adding the example?
