### ISSUE TITLE
Define the excluded Components list

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#279]
After #278 has been merged, we need to set a list of excluded components

**Comment by oscerd** [comment]
I'd like to revive the discussion. There are number of aws components that don't make sense as connector. For example kms,iam,eks,ecs etc. Also some others.
I'd like to limit the number of connectors to be able to speed up the release process and release often

@valdar @orpiske can you share your pov

**Comment by orpiske** [comment]
> I'd like to revive the discussion. There are number of aws components that don't make sense as connector. For example kms,iam,eks,ecs etc. Also some others.
> I'd like to limit the number of connectors to be able to speed up the release process and release often
> 
> @valdar @orpiske can you share your pov

+1. I think this is a good idea and I agree with you that it can simplify release, maintenance and possibly even reduce any risk of extra work due to CVEs in dependencies. All in all, a welcome change, IMHO. 

It would be good - more as a safe proof for the future - to document our thought process in removing them. My thinking is that we might need to refer to that should the need arise. 

Lastly, we already have a lot of connectors. I don't know how you plan to do that, but it might be difficult for a single person to review them all. I volunteer to help with the effort to trim them.

**Comment by oscerd** [comment]
Let me start by removing these:

camel-aws2-ec2
camel-aws2-ecs
camel-aws2-eks
camel-aws2-iam
camel-aws2-kms
camel-aws2-mq
camel-aws2-msk
camel-aws-ec2
camel-aws-ecs
camel-aws-eks
camel-aws-iam
camel-aws-kms
camel-aws-mq
camel-aws-msk

This components have only the producer side and are used to create, delete, list and describe stuff in AWS services- Lambda is similar, but you have the opportunity to invoke a function through the producer. So we should leave it. I'll open a first PR by removing these connectors.

**Comment by oscerd** [comment]
I think we need to remove also 
- camel-mock
- camel-ref
- camel-robotframework (for testing)

I'll remove this and then I'll continue the investigation

**Comment by omarsmak** [comment]
I think as well, camel-kafka doesn't make sense to be there since the whole thing is running based on kafka.

**Comment by omarsmak** [comment]
As well, camel-debezium components I think in my opinion they don't need to be there as well since Debezium is originally a Kafka Connect connector.

**Comment by oscerd** [comment]
Removing
- camel-kafka
- camel-debezium-*
- camel-dataset
- camel-dataset-test

**Comment by oscerd** [comment]
Removing

- camel-digitalocean

**Comment by oscerd** [comment]
Removing

- browse component
- class component

**Comment by oscerd** [comment]
Removed bean connector

**Comment by oscerd** [comment]
Removing

- bean-validator component
- jing component

**Comment by oscerd** [comment]
I think aws*-translate too, should be removed, it just set the translation in the body of the camel exchange

**Comment by valdar** [comment]
Hello, has commented in the relative PR I feel that `camel-kafka` covers a legitimate usecase (even though there are other options to accomplish the same in the kafka broader ecosystem) that is propagating events between different kafka clusters.

As per the `aws-*` sink only components, creating entities in aws based on some events on a topic seems a reasonable usecase to me. Imagine, for instance, a kafka topic with the "new user created" event, and you want to generate an was IAM in response to that...

**Comment by oscerd** [comment]
I'll add the aws again. For the kafka connector I'm not sure, but it doesn't cost to add it again. So let me do this before 0.6.0
