### ISSUE TITLE
Outdated camel-dependencies version?

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#297]
Hey @oscerd / @valdar, I noticed that the code is using [camel-dependencies:3.3.0 ](https://github.com/apache/camel-kafka-connector/blob/286dc141ab84911f19319a1e0a865137c7fb3927/pom.xml#L26). 

I am not sure if this is intentional or not, but since we have upgraded to Camel 3.4, I was wondering if it should use the 3.4.0 one. What do you think?

**Comment by oscerd** [comment]
I'm on it, building everything now :-)

**Comment by orpiske** [comment]
@oscerd ahhh, awesome, thanks!

**Comment by oscerd** [comment]
This is something I keep on forgetting even in other subprojects. I'm sorry.
