### ISSUE TITLE
INFRA - Turn off mail noise to Camel @dev mailing list

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-kafka-connector#30]
We need to turn off the noise from camel-kafka-connector on the @dev mailibg list
like we did for the other projects
its spammed with gitbox messages now
https://camel.465427.n5.nabble.com/Camel-Development-f479097.html

**Comment by oscerd** [comment]
Can you raise this to INFRA?

**Comment by oscerd** [comment]
https://issues.apache.org/jira/browse/INFRA-19548

**Comment by oscerd** [comment]
Opened.

**Comment by valdar** [comment]
done.
