### ISSUE TITLE
run integration test insided github actions?

### ISSUE THREAD

**Issue by valdar** [apache/camel-kafka-connector#31]

**Comment by valdar** [comment]
See if it is possible to have integrations tests running as github actions, not as heach PR but once in a while (nightly?).

**Comment by orpiske** [comment]
Personally, I prefer having the tests run for each PR, as it makes it easier to spot some issues. 

I also think it would also be interesting to check if there's something more stable to run the tests. Looking at the jobs for the PRs the project has had, it seems to me that there are few false negatives happening from time to time. For example: 

- https://github.com/apache/camel-kafka-connector/pull/33/checks?check_run_id=340682725
- https://github.com/apache/camel-kafka-connector/pull/29/checks?check_run_id=340320189

Looking at them, you notice that they are not related to the subject being tested, but apparentlyt the infra running the test.

**Comment by valdar** [comment]
If the time is reasonable we can have them for each PR. Not sure about resources available though...

**Comment by valdar** [comment]
I think from some RPs experience, the time is quite reasonable. We can keep them for each PR. I just disabled them by default (but enabled them in GitHub actions runs): https://github.com/apache/camel-kafka-connector/commit/2658307e2ad078dc945ae98d4b0b8d9dd769b94a
