### ISSUE TITLE
CAMEL-15063 work-around may be removed

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#310]
Since we have moved to 3.4, I think we can remove this workaround for the aforementioned issue: https://github.com/apache/camel-kafka-connector/blob/master/connectors/camel-salesforce-kafka-connector/src/main/java/org/apache/camel/component/salesforce/SalesforceComponentCKC.java#L22

**Comment by oscerd** [comment]
@orpiske can you open a PR for this? Thanks.

**Comment by orpiske** [comment]
@oscerd absolutely. I can take care of this. I'll send a PR tomorrow/after tomorrow after I finish the remaining HDFS checks :)

**Comment by orpiske** [comment]
Quick status update: I have the PR ready and I am planning to send it tomorrow morning if it passes the Salesforce tests on CI.
