### ISSUE TITLE
How to break messages when ingesting into kafka

### ISSUE THREAD

**Issue by akhileshacc** [apache/camel-kafka-connector#313]
I wanted to break messages before sending to kafka endpoint.
Is it possible to do with processors ?

I am trying to send S3 files data to kafka using s3 and kafka components.
```
from("aws-s3://bucketname?args=....")
.to("kafka:test1?brokers=localhost:9092")
```

How do i break messages before sending to kafka ?

**Comment by oscerd** [comment]
Hello.

1. What do you mean with break messages?
2. This is the issue tracker for camel-kafka-connector, but you're using camel. You should ask on the camel users mailing list or dev mailing list: https://camel.apache.org/community/mailing-list/ and ask there.

**Comment by akhileshacc** [comment]
1. If text file has 10mb data, can i pick 10 records with 1mb of data and then store it.
2. Sure will do so.

**Comment by oscerd** [comment]
You can implement a processor. Each S3ObjectInputStream can be read and you can read the data for example 1 Mb

**Comment by oscerd** [comment]
By the way, it's better to discuss this on the mailing list to avoid confusion.

**Comment by akhileshacc** [comment]
Thanks for the help.
