### ISSUE TITLE
aws2S3connector: moveAfterRead true bucket not created

### ISSUE THREAD

**Issue by rbaumgar** [apache/camel-kafka-connector#339]
aws2S3connector 
If I set moveAfterRead=true and camel.source.endpoint.destinationBucket=camel-backup and camel-backup does not exist -> error!
even camel.source.endpoint.autoCreateBucket=true (default)!

**Comment by oscerd** [comment]
The option if for the bucketName in the component the auto reaction of destination bucket for that specific operation is not supported. I'll add this on Camel. Can you create a jira issue about this on https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-15339?filter=allopenissues

**Comment by oscerd** [comment]
It must exist for the moment

**Comment by rbaumgar** [comment]
https://issues.apache.org/jira/browse/CAMEL-15347

**Comment by oscerd** [comment]
Fixed, it will be available in camel 3.5.0. I'll close this once we update to that.

**Comment by oscerd** [comment]
We updated to 3.5.0 and this will be available in 0.5.0
