### ISSUE TITLE
Discussion: troubleshooting documentation?

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#381]
Do you think we should have a troubleshooting documentation/page with some of the common errors and problems that people face when they use the connectors? Some things I have in mind that we could add some notes about: 

- Installing the connectors in a directory structure that is incompatible with Kafka Connect
- Missing or incorrect converters
- Missing dependencies
- Known incompatibilities 
- Known limitations

**Comment by oscerd** [comment]
+1
