### ISSUE TITLE
aws2-S3-connector: (gzip/zip) compression with sink

### ISSUE THREAD

**Issue by harwee** [apache/camel-kafka-connector#387]
I am using  aws2-S3 connector with aggregation. Is there a way to compress the final object that is put into the S3 bucket?

**Comment by orpiske** [comment]
I think you probably need to write a custom aggregator for it.

**Comment by oscerd** [comment]
Just for your information I created an example using the zipAggregationStrategy https://github.com/apache/camel-kafka-connector-examples/tree/master/aws2-s3/aws2-s3-sink-with-zip-aggregation
