### ISSUE TITLE
Add an example of FHIR connector's usage

### ISSUE THREAD

**Issue by mschuch** [apache/camel-kafka-connector#402]
Hi i wanted to try the kafka fhir source connector with the following property file:
```
{
	name: "FhirKAfka",
	config: {
		connector.class: "org.apache.camel.kafkaconnector.fhir.CamelFhirSourceConnector",
		key.converter: "org.apache.kafka.connect.storage.StringConverter",
		value.converter: "org.apache.kafka.connect.storage.StringConverter",
		camel.source.url: "http://hapi.fhir.org/baseR4/Patient/1254233",
		camel.source.path.apiName: "read",
		camel.source.path.methodName: "Patient"
	}
}
```
Now i am stuck which of the properties if have to use, how I can test it with the open fhir test server.
Which of the properties are mandatory? I think the endpoint should look like:

`fhir//:apiName/methodName?[options] `

I am just lost and need an example how that can work. Thank you.

**Comment by oscerd** [comment]
I'll try to create an example for this

**Comment by oscerd** [comment]
Done here https://github.com/apache/camel-kafka-connector-examples/tree/master/fhir
