### ISSUE TITLE
Introduce Error Handling Options possibilities

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#407]
We can reuse the error handling coming from Camel, like we are doing for aggregation with Options and Parameters

**Comment by oscerd** [comment]
We could for example, set redeliveries, for example
Or define a custom Error Handler or do nothing.

**Comment by orpiske** [comment]
> We could for example, set redeliveries, for example
> Or define a custom Error Handler (for custom I mean tuning the error handler options) or do nothing and just fail.

I was thinking about error handling today and I was wondering: what if we allowed configuring the default error handler so that it can send the errors to Kafka's dead letter queue?

**Comment by oscerd** [comment]
You can do that already. It's already available as kafka connect option. This issue was focused on camehandling

**Comment by oscerd** [comment]
If you intend to send to dlq through camel at camel context level, it"s not available yet, but I don't think it makes sense.

**Comment by orpiske** [comment]
> You can do that already. It's already available as kafka connect option. This issue was focused on camel error handling

> If you intend to send to dlq through camel at camel context level, it"s not available yet, but I don't think it makes sense.

So, I think I understand why I was confused*. There is a bug in the way we are handling the DLQ within the Kafka Connect API. I will provide a reproducer + soon.
