### ISSUE TITLE
camel-azure-storage-queue-kafka-connector: Unknown parameter 'accountName'

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#409]
When trying to run the `camel-azure-storage-queue-kafka-connector` setting the properties directly (ie.: not via the URL), the code seems to fail to do so and fails with:

```org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: azure-storage-queue://test-queue23?accountName=devstoreaccount1 due to: Failed to resolve endpoint: azure-storage-queue://test-queue23?accountName=devstoreaccount1 due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{accountName=devstoreaccount1}]``` 

I'll provide a reproducer along w/ the integration test for this one.

**Comment by oscerd** [comment]
cc @omarsmak

**Comment by omarsmak** [comment]
Sorry @orpiske, the docs were not clear in some parts, the correct url should be like this :
`azure-storage-queue:/accountName/queueName?options`. If you get it working, please don't hesitate to correct the docs as I am currently in vacation :)

**Comment by orpiske** [comment]
Thanks @oscerd and @omarsmak. 

TBH, I think the problem is on the way we are auto-generating this URL. To explain a bit further: I have 2 scenarios on the test. In one of them, the URL is setup manually (ie.: using `camel.sink.url`) and it works (the URL used is pretty much the same as the one you showed). On the other scenario, where I set everything via properties (ie.: `camel.sink.path.accountName`, `camel.sink.path.queueName`, etc), then it appears it creates the URL incorrectly.

**Comment by orpiske** [comment]
So, continuing the investigation on this one, it seems to me that this is the cause for the wrong URI: 

- [azure-storage-queue.json](
https://github.com/apache/camel/blob/master/components/camel-azure-storage-queue/src/generated/resources/org/apache/camel/component/azure/storage/queue/azure-storage-queue.json#L17 ) from master (3.5)
- [azure-storage-queue.json](
https://github.com/apache/camel/blob/camel-3.4.x/components/camel-azure-storage-queue/src/generated/resources/org/apache/camel/component/azure/storage/queue/azure-storage-queue.json#L17) from camel-3.4.x

Since this (seems) to be fed into the [AbstractCamelCatalog.doAsEndpointUri](https://github.com/apache/camel/blob/camel-3.4.x/core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/AbstractCamelCatalog.java#L695) which is called - at one point - as part of the [TaskHelper.buildUrl](https://github.com/apache/camel-kafka-connector/blob/master/core/src/main/java/org/apache/camel/kafkaconnector/utils/TaskHelper.java#L42).

I am not sure, yet, how this one is generated.

**Comment by orpiske** [comment]
For the record, I think the format of the syntax in that json file should be `azure-storage-queue:/accountName/queueName`.

**Comment by oscerd** [comment]
Can you open an upstream issue?

**Comment by orpiske** [comment]
> Can you open an upstream issue?

Absolutely. Just collecting the last bit of information here and I'll open one for this.

**Comment by orpiske** [comment]
@oscerd done :) 

- this one is for the camel-azure-storage-queue: https://issues.apache.org/jira/browse/CAMEL-15499
- this one is for the camel-azure-storage-blob, which seems to suffer from the same problem, but I haven't validated it: https://issues.apache.org/jira/browse/CAMEL-15500

**Comment by omarsmak** [comment]
I see it fixed, isn't @orpiske @oscerd ? Thanks for the PRs :)

**Comment by oscerd** [comment]
Fixed. It will be in 3.6.x
