### ISSUE TITLE
Unreleased Resource: Database

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/camel-kafka-connector#436]
https://github.com/apache/camel-kafka-connector/blob/c26a551672e9c67216900dc4debbe041f512057a/tests/itests-jdbc/src/test/java/org/apache/camel/kafkaconnector/jdbc/client/DatabaseClient.java#L45

The program can potentially fail to release a database resource.

**Comment by oscerd** [comment]
Thx

**Comment by oscerd** [comment]
It's just a test
