### ISSUE TITLE
Define a default naming for converters, transforms and aggregation packages

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#439]
We need to list what we currently have in our codebase and move our converters, transforms and aggregation in a default named package.

In this way, we could search for a specific package and automatically generated/lists the available converters, transforms and AggregationStrategies defined for each converters (if any).

In this way we should be able to add more information for end users.

My proposal is to use:
- org.apache.camel.kafkaconnector.<connector_name>.converters
- org.apache.camel.kafkaconnector.<connector_name>.transforms
- org.apache.camel.kafkaconnector.<connector_name>.strategies

Actually we are still on time because we have a little amount of this stuff, but in future this would a pain.

**Comment by orpiske** [comment]
> My proposal is to use:
> 
>     * org.apache.camel.kafkaconnector.<connector_name>.converters
> 
>     * org.apache.camel.kafkaconnector.<connector_name>.transforms
> 
>     * org.apache.camel.kafkaconnector.<connector_name>.strategies

+1. I think this looks straight to the point and consistent. My only comment would be regarding `transforms`. Wouldn't it be more precise to use `transformers`?

**Comment by oscerd** [comment]
Yeah, it makes sense, I'll merge the PR and then rework on package naming.

**Comment by oscerd** [comment]
Done
