### ISSUE TITLE
Unstable test: CamelSourceTaskTest.testSourcePollingTimeout

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#55]
I am noticing some sporadic failures on the CamelSourceTaskTest.testSourcePollingTimeout test. From time to time I get this: 

```
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.009 s <<< FAILURE! - in org.apache.camel.kafkaconnector.CamelSourceTaskTest
[ERROR] org.apache.camel.kafkaconnector.CamelSourceTaskTest.testSourcePollingTimeout  Time elapsed: 3.033 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<2>
	at org.apache.camel.kafkaconnector.CamelSourceTaskTest.testSourcePollingTimeout(CamelSourceTaskTest.java:196)
```

I did not have time to investigate it in depth, but I can take when I get back.

**Comment by valdar** [comment]
I fear we need to relax the constraint here: https://github.com/apache/camel-kafka-connector/blob/master/core/src/test/java/org/apache/camel/kafkaconnector/CamelSourceTaskTest.java#L196 to a "greater than". I can take care of that.
