### ISSUE TITLE
Create example for camel-resteasy-kafka-source-connector

### ISSUE THREAD

**Issue by LeonardoBonacci** [apache/camel-kafka-connector#565]
Hi all,

Thanks to all contributors: this is a great and promising project!

I'm trying to set-up the camel-resteasy-kafka-source-connector, with the following - largely guessed - connector configuration 
```
{
  "name": "camel-resteasy",
  "config": {
      "tasks.max":1,
      "topics": "foo",
      "connector.class":"org.apache.camel.kafkaconnector.resteasy.CamelResteasySourceConnector",
      "key.converter":"org.apache.kafka.connect.storage.StringConverter",
      "value.converter": "org.apache.kafka.connect.json.JsonConverter",
      "value.converter.schemas.enable": false,

      "camel.source.path.httpUri": "/easy",
      "camel.source.endpoint.resteasyMethod": "POST"
  }
}
```
It's just a experiment, but I cannot figure out how to access the connector and no documentation is provided.
My Kafka Connect node is accessible on the default localhost:8083.

Question is: how to configure camel.source.path.httpUri? On a local setup - having just the Kafka Connect node running- on which host is the connector (made) accessible?

Some documentation/explanation/example would be very much appreciated.
Cheers!

**Comment by valdar** [comment]
Hi @LeonardoBonacci I am not sure I completely get what you are trying to achieve; do you want to expose a rest endpoint trough a camel-kafka-connector?

How do you run the connector? 
You mention a running local Kafka Connect cluster,  how do you run that one as well?

**Comment by LeonardoBonacci** [comment]
Hi @valdar exactly that. I want to expose a rest endpoint through a camel-kafka-connector.
The Kafka Connect cluster runs through docker-compose now, but in the future it will run in a Kafka Connect cluster in Kubernetes using Strimzi operators.

**Comment by oscerd** [comment]
Basically it's a camel context behind these connectors. We still need to check this stuff, but as far as you have a consuming side in the component you'll get an autogenerated source connector.

**Comment by oscerd** [comment]
In terms of aurogeneration and docs there is nothing to update

**Comment by oscerd** [comment]
I think the packaged connectors doesn't have all the required bits, at least it seems we are missing something @LeonardoBonacci

**Comment by LeonardoBonacci** [comment]
All good. Thanks for answering! 
I close this issue for now since there are many more important issues on your backlog ;)
