### ISSUE TITLE
Strimzi 0.20: Lets test early with Release candidate

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#581]
The first one, is already out. We can do this on camel-master
https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.20.0-rc1

**Comment by orpiske** [comment]
@oscerd if you want, I can prepare this.

**Comment by oscerd** [comment]
Sure, but I'd like to wait for the final release, so maybe we could have a profile for testing with release candidates? Not sure. This would probably require updating to kafka 2.6.0 too

**Comment by orpiske** [comment]
I'm trying the following:

**Comment by orpiske** [comment]
I am not sure if the `-Dkafka.version=2.6.0` yet will actually manage to override the version, but the rest should definitely run the tests against Strimzi 0.20 rc1. I am running a build here and will let you know soon.

**Comment by oscerd** [comment]
Thanks, sounds good. We can do this and if it works we can create a profile to be enabled with a gh action for example.

**Comment by orpiske** [comment]
That sounds like a good plan +1.

**Comment by orpiske** [comment]
@oscerd looking at the GH actions, it does not seem to have run. I believe I need to cherry-pick the action into master.

**Comment by oscerd** [comment]
yes

**Comment by orpiske** [comment]
Worked after cherry-picking. Therefore, marking this one as closed.
