### ISSUE TITLE
Include possible enum values in Catalog

### ISSUE THREAD

**Issue by apupier** [apache/camel-kafka-connector#645]
The Camel kafka Connector Catalog currently doesn't contain information on possible values in case of enumeration.

it would be nice to provide them so that tooling support can be improved by proposing them via completion.

**Comment by apupier** [comment]
start looking at it.

technical help provided by Andrea C.:
`need to have a look at how the defaultValue are set in generic camel-catalog and modify the model we are using in ckc by including them into a default value field.`

**Comment by apupier** [comment]
default values are already provided:
https://github.com/apache/camel-kafka-connector/blob/314eee947e6f9c979a9c1ddbcd5516c3f51b6539/camel-kafka-connector-catalog/src/main/java/org/apache/camel/kafkaconnector/catalog/CamelKafkaConnectorCatalog.java#L136
https://github.com/apache/camel-kafka-connector/blob/314eee947e6f9c979a9c1ddbcd5516c3f51b6539/camel-kafka-connector-catalog/src/test/java/org/apache/camel/kafkaconnector/catalog/CamelKafkaConnectorCatalogTest.java#L81

the missing part is the list of available enums

**Comment by apupier** [comment]
in Core Camel Catalog, the values are provided in a field `enum`, for instance:

https://github.com/apache/camel/blob/cffe3d077020cafee4ae39935c3e4c189a6976b8/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/activemq.json#L30

**Comment by oscerd** [comment]
Should have been done.
