### ISSUE TITLE
Add Simple Language support 

### ISSUE THREAD

**Issue by LeonardoBonacci** [apache/camel-kafka-connector#667]
To increase general flexibility for all connectors it would be great if it were possible to somehow use the Camel Simple Language (or at least a subset of it).

Reason being: I'm trying to use the sftp-source connector and receive this value in my Kafka Topic: _RemoteFile[testfile.txt]_

Reading the file works, but in the [docs](https://camel.apache.org/camel-kafka-connector/latest/connectors/camel-sftp-kafka-source-connector.html) I cannot find a property that allows me to pre-manipulate the data. I'm missing the tools to 'massage' the record/data before it receives my StringConverter (or single message transformer - if used). I'm stuck at this point and imagine many more use-cases that face a similar problem.

This functionality - if possible at all - in combination with the [open issue to write Processors](https://github.com/apache/camel-kafka-connector/issues/22) would allow for great power.

Apologies if I'm requesting something absurd. I'm coming from the 'Kafka side' and being relatively new to Camel - I see great potential in the camel kafka connector project.

**Comment by oscerd** [comment]
If you need to use a processor i believe you should use plain camel. This is a first suggestion. The simple language is already supported. In your connector options you can already use stuff like ${body} or headers. Like here for example: https://github.com/apache/camel-kafka-connector-examples/blob/master/aws2-s3/aws2-s3-sink-with-aggregation/config/CamelAWS2S3SinkConnector.properties#L31

If you need to manipulate the data like passing through a bean or doing complex simple expression, you should use camel directly, through the camel-kafka component..

**Comment by LeonardoBonacci** [comment]
It's already available? That sounds great!

Do you have a suggestion on to which sftp configuration property can be used to read the message body?

https://camel.apache.org/camel-kafka-connector/latest/connectors/camel-sftp-kafka-source-connector.html

Cheers!

**Comment by oscerd** [comment]
I'm working on an example, for this purpose :-)

I'll post it here, probably we'll need to introduce a little transform

**Comment by oscerd** [comment]
https://github.com/apache/camel-kafka-connector-examples/tree/master/sftp/sftp-source

Here is an example.

**Comment by LeonardoBonacci** [comment]
Works like a charm! Your transform works much better than my improvised one.
Thanks again and I will close this ticket.
