### ISSUE TITLE
Flaky test: CamelSinkCassandraITCase

### ISSUE THREAD

**Issue by valdar** [apache/camel-kafka-connector#67]
I have seen `CamelSinkCassandraITCase` sporadically failing and claiming to have received 9 out of 10 records.
Is it possible that there might be some race condition around here https://github.com/apache/camel-kafka-connector/blob/master/tests/src/test/java/org/apache/camel/kafkaconnector/sink/cassandra/CamelSinkCassandraITCase.java#L112 ?

**Comment by valdar** [comment]
@orpiske ?

**Comment by orpiske** [comment]
> @orpiske any idea on this one?

I think so. It looks like I inadvertently added a time-of-check-time-of-use kind of bug. I was looking at the [hasData](https://github.com/apache/camel-kafka-connector/blob/master/tests/src/test/java/org/apache/camel/kafkaconnector/clients/cassandra/dao/TestDataDao.java#L82) and I am only checking if some amount of data is in the table and not if the right amount of data is there. This could cause the wait to release too early and the subsequent check for the right amount of messages to fail. 

I'll send a PR to fix this.

**Comment by valdar** [comment]
Sounds reasonable to me!
