### ISSUE TITLE
Provide validation of properties file from the catalog

### ISSUE THREAD

**Issue by apupier** [apache/camel-kafka-connector#671]
The Camel core catalog is providing a validation mechanism. For instance, by checking that parameters used are valid. This validation is used by camel maven plugin and by Camel Language Server.

It would be interesting to provide validation too for properties file.

- [ ] Provide API method taking a properties string text and returning a list of Validation result. The validation result should contain at least a message and the range.
- [ ] Validate that property key is valid
- [ ] Validate that camel.(source|sink) corresponds to the source sink nature of the connector.class
- [ ] Validate that connector class and camel.(source|sink).url is valid
- [ ] Validate that required properties are available
- [ ] Validate that there is no duplicated keys (with the variation of dashed names and camelCase name)
- [ ] Validate that values are boolean for boolean properties
- [ ] Validate that values for enum are valid
- [ ] Validate that camel.(source|sink).url is not mixed with camel.component.* notations

**Comment by apupier** [comment]
question: is it relevant to have it in Camel Kafka Connector project? given that the properties files seems to be usually standalone, not inside a Maven or Gradle project. Maybe this would be better to implement it only in Camel Language Server side.

**Comment by apupier** [comment]
if part of Catalog, is it possible to reuse some LSP4J API for Range, or perhaps even org.eclipse.lsp4j.Diagnostic?

**Comment by oscerd** [comment]
I do think it makes sense to have it as part of Camel Language Server

**Comment by apupier** [comment]
to provide range, it might be useful to reuse the PropertiesParser from Microprofile/Quarkus Language Server https://github.com/eclipse/lsp4mp/blob/master/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/model/parser/PropertiesParser.java there are discussions to extract it https://coreos.slack.com/archives/CK14U2L4V/p1604591998095300

**Comment by apupier** [comment]
> I do think it makes sense to have it as part of Camel Language Server

created Epic https://issues.redhat.com/browse/FUSETOOLS2-905 to provide the validation at Camel language Server only.
