### ISSUE TITLE
Provide API in Camel Connector Catalog to retrieve Camel Kafka Basic configuration

### ISSUE THREAD

**Issue by apupier** [apache/camel-kafka-connector#679]
Several options are considered as "basic configuration". They are specific to Camel Kafka Connector. Providing them in the catalog will allow to provide tooling for it.

https://camel.apache.org/camel-kafka-connector/latest/basic-configuration.html

**Comment by apupier** [comment]
starting to look at it.

**Comment by oscerd** [comment]
This has been done.
