### ISSUE TITLE
Add test for AWS 2 SNS

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#700]
Adding an issue for me. I already have it ready and can merge once we move to 3.7.

**Comment by orpiske** [comment]
Done.

**Comment by oscerd** [comment]
@orpiske if this stuff is done for 0.8.0, add also the milestone 0.8.0, so they will appear in the camel release page :-) Thanks!

**Comment by orpiske** [comment]
Ahhhh, cool. I think I have to add it to a few others, thanks @oscerd
