### ISSUE TITLE
Possibly moving Integration tests in a separated repository?

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#746]
At some point we may end up having a lot of IT tests that may slow down the build. We may maintain just a subset of IT Tests in that case in main repo and moving the other in a different repo. What's your thought on this @valdar @orpiske ?

**Comment by orpiske** [comment]
I agree that at this point, they are already taking far too long to run. 

However,  I'd possibly keep them in this repo. I think we need to start filtering some slow tests in such a way that they can be enabled at will. 

With junit 5 we can annotate the tests with

```
@EnabledIfSystemProperty(named = "enable.tests.slow", matches = "true"
```

Then, we can enable those tests when needed by using `mvn -Denable.tests.slow=true ...` 

Keeping them separate makes it a bit hard for writing, debugging and test automation IMHO.

**Comment by oscerd** [comment]
Sounds good, but we need to track down the slow ones.

**Comment by orpiske** [comment]
Agreed. I think I have some data about these. I'll try to share today or tomorrow.

**Comment by valdar** [comment]
+1 on leaving the tests on the same repo and have a way to enable them. I am not sure if a opt in or opt out approach is better though...

**Comment by orpiske** [comment]
![Screenshot_2020-11-27 camel-kafka-connector #246 Test Results  Jenkins (1)](https://user-images.githubusercontent.com/1851560/100428324-11642180-3094-11eb-9d24-5d92111f784c.png)

This is the duration report from a personal CI I have, which runs the tests in multiple configurations (JDKs, w/ Strimzi, Salesforce tests, etc). AWS ones seems to be very big offenders in terms of test duration. 

IMHO, we could probably leave them for running only on Apache CI. My vote would be for a explicit opt-in (via -Denable.tests.slow=true) and I can send a proposal PR later today if you all agree @valdar, @oscerd and anyone else that would like to step in and comment.

**Comment by oscerd** [comment]
+1 for this approach

**Comment by orpiske** [comment]
Thanks!

Let's see how it goes: https://github.com/apache/camel-kafka-connector/pull/749

**Comment by oscerd** [comment]
I think this is ok through #749
