### ISSUE TITLE
Create binary distribution

### ISSUE THREAD

**Issue by zregvart** [apache/camel-kafka-connector#754]
With #524 we have the sources distribution as a ZIP file, we should also create a binary distribution containing the ZIP packages of connectors.
We have these already deployed to the Maven Central I think a ZIP file containing connector ZIP packages could convenient for users. This way we can link to a single ZIP file from the website for downloads rather than having a list of all connectors which would be a bit of a pain to maintain on the website.

**Comment by oscerd** [comment]
+1

**Comment by zregvart** [comment]
I've spoken with @valdar and it seems that a binary ZIP-of-ZIPs would be 10GB, we should probably check with INFRA if that's okay with them. Perhaps as an alternative we could create a installer-like tool that would download/assemble (as needed) the connector ZIP file from Maven central. Might be a good idea to have such a tool to allow folk to manage the configuration of the connector as well.
