### ISSUE TITLE
Run slow tests on Apache CI

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#786]
Hey @oscerd @valdar based on that discussion we had about some testing getting slower and slower, I think we should move some of the tests to the Apache CI. Looking at what we have there today it seems we are only [running the unit tests](https://ci-builds.apache.org/job/Camel/job/Camel-Kafka-Connector%20Daily/job/master/104/testReport/). 

Thoughts? Objections?

**Comment by oscerd** [comment]
+1

**Comment by orpiske** [comment]
So, it looks like the big problem is working around the new pull limits on the Docker hub. I think we may work-around those if we authenticate to the hub and add that token to the CI. 

@oscerd @valdar any suggestions on how we could possibly do this?

**Comment by oscerd** [comment]
We need to ask infra

**Comment by orpiske** [comment]
@oscerd thanks. I will open a ticket for this.

**Comment by orpiske** [comment]
https://issues.apache.org/jira/browse/INFRA-21197

**Comment by valdar** [comment]
I think this is done given the resolution of https://issues.apache.org/jira/browse/INFRA-21197, @orpiske feel free to reopen it if needed.
