### ISSUE TITLE
Support camel dataformat configuration for marshaller/unmarshaller

### ISSUE THREAD

**Issue by luigidemasi** [apache/camel-kafka-connector#816]
there are some dataformats that support configuration parameters, but at the moment is just possible to specify the dataformat id in `camel.source.marshal` and `camel.source.unmarshal`

**Comment by valdar** [comment]
So based on https://github.com/apache/camel-kafka-connector/pull/855 this should have already worked, but a bug in camel was discovered, reported and fixed see https://issues.apache.org/jira/browse/CAMEL-16032.

This can be closed once we use a version of camel that has the fix.
NOTE: this test must be updated https://github.com/apache/camel-kafka-connector/commit/712917ea9274feaf13bb5f4eeb2971b4f0c6e234
