### ISSUE TITLE
Add Mongodb examples

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#823]
To camel-kafka-connector-examples repo

**Comment by orpiske** [comment]
Sample configuration for the MongoDB sink:

```
connector.class=org.apache.camel.kafkaconnector.mongodb.CamelMongodbSinkConnector
camel.sink.endpoint.operation=insert
camel.sink.endpoint.collection=testRecords
tasks.max=1
topics=org.apache.camel.kafkaconnector.mongodb.sink.CamelSinkMongoDBITCase
name=CamelMongoDBSinkConnector
value.converter=org.apache.kafka.connect.storage.StringConverter
camel.sink.path.connectionBean=mongo
camel.beans.mongo=#class:com.mongodb.client.MongoClients#create('mongodb://localhost:32772')
camel.sink.endpoint.database=testDB
key.converter=org.apache.kafka.connect.storage.StringConverter
```

An important bit for the mongoDB sink is to configure the `camel.beans.mongo` property correctly. In this case, it is setting the bean to be created by calling the method create passing the URL of the mongodb instance (mongodb://localhost:32772). This should be configured accordingly to your setup.

**Comment by oscerd** [comment]
Moved to https://github.com/apache/camel-kafka-connector-examples/issues/242
