### ISSUE TITLE
Support Parquet input Files using HDFS (compressed or not compressed)

### ISSUE THREAD

**Issue by matt12eagles** [apache/camel-kafka-connector#840]
Support Parquet input file formats using HDFS connector. Parquet is widely used in the HDFS world, would be awesome to be able to use parquet with the standard compressions (snappy, gzip, none) for this connector. I dont think a great open source HDFS source that supports parquet and kerberos exists, so it would be big for the kafka community.

**Comment by oscerd** [comment]
Duplicate?

**Comment by matt12eagles** [comment]
it is! sorry! closing! Got an error when submitting the one.
