### ISSUE TITLE
Remove changelog gh action

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#842]
ASF doesn't allow it anymore. We need to find an official action for it

**Comment by orpiske** [comment]
Maybe this would do the trick: http://maven.apache.org/plugins/maven-changelog-plugin/

**Comment by oscerd** [comment]
I don't think it's really useful in this case, we need to have a look at gh issues and PR and the maven plugin is not for that.. We need to update the changelog by hand I guess.

**Comment by oscerd** [comment]
I think we can use milestones: I created this https://github.com/apache/camel-kafka-connector/milestone/3 for 0.8.0
