### ISSUE TITLE
add itests for camel-cxf-kafka-connector

### ISSUE THREAD

**Issue by ffang** [apache/camel-kafka-connector#873]

**Comment by ffang** [comment]
Hi @valdar, @oscerd, @orpiske ,

Happy Friday!

I just sent a PR for the cxf-itests, including both Source and Sink CXF connector itests case.

And I have a few questions, I will add comments in the PR near the code piece I have questions. Please take a look at this PR!

Thanks!
Freeman

**Comment by orpiske** [comment]
Thanks @ffang! I will take a look at it :)

**Comment by valdar** [comment]
I think some itest for cxf are there (I fixed some myself for camel 3.9.0 release) so I would close this.
