### ISSUE TITLE
[Question] liveness and readiness probes example for camel-kafka-connector

### ISSUE THREAD

**Issue by ruchirvaninasdaq** [apache/camel-kafka-connector#874]
Hello, 

Is there any liveness and readiness probes example for camel-kafka-connector? 

I am using strimzi operator(0.20.0) for deployment. https://github.com/strimzi/strimzi-kafka-operator/blob/master/install/cluster-operator/041-Crd-kafkaconnect.yaml#L249 

Thanks you!!

**Comment by orpiske** [comment]
> Hello,
> 
> Is there any liveness and readiness probes example for camel-kafka-connector?
> 
> I am using strimzi operator(0.20.0) for deployment. https://github.com/strimzi/strimzi-kafka-operator/blob/master/install/cluster-operator/041-Crd-kafkaconnect.yaml#L249
> 
> Thanks you!!

I don't think we have an example for that, but I think you could probably try to probe the connect rest API and check if the the worker status is "RUNNING" and the task state is "RUNNING". 

Also, I suspect that this would be something Strimzi might already have ... so, it would be worth checking on that end as well.

**Comment by ruchirvaninasdaq** [comment]
Ok thank you!! I just wanted to check with team if I need to check (verify) anything specific for camel connector also.
