### ISSUE TITLE
The camel-kafka-connector artifacts pulls number of dependencies

### ISSUE THREAD

**Issue by jerrinot** [apache/camel-kafka-connector#9]
I am trying to use this project to [integrate](https://github.com/hazelcast/hazelcast-jet-contrib/pull/30) with Hazelcast Jet. It works pretty nicely, well done!
```java
public final class KafkaConnectTest {
    private static final String BROKER_URL = "tcp://10.0.0.113";
    private static final String TOPIC = "test";

    public static void main(String[] args) {
        JetInstance jet = Jet.newJetInstance();

        Pipeline pipeline = Pipeline.create();
        pipeline.readFrom(KafkaConnectSources.connect(kafkaConnectProps()))
                .withoutTimestamps()
                .map(record -> new String((byte[])record.value()))
                .writeTo(Sinks.logger());

        JobConfig jobConfig = new JobConfig();
        Job job = jet.newJob(pipeline, jobConfig);
        job.join();
    }

    private static Properties kafkaConnectProps() {
        Properties properties = new Properties();
        properties.setProperty("name", "camel-source-connector");
        properties.setProperty("connector.class", "org.apache.camel.kafkaconnector.CamelSourceConnector");
        properties.setProperty("camel.source.url", "paho:" + TOPIC + "?brokerUrl=" + BROKER_URL);
        return properties;
    }
}
```
There is one thing I don't quite understand: The main artifact (camel-kafka-connector) pulls a [number of dependencies](https://github.com/apache/camel-kafka-connector/blob/87cc89fadfeb22ec146cdcc1410f055f67384e05/core/pom.xml#L48-L83) which I don't need and I have to manually exclude. Is there any reason for this?

**Comment by oscerd** [comment]
This is something we still need to optimize. Thanks for reporting this and for your feedback :-)

**Comment by jerrinot** [comment]
That's what I thought! Would you accept a Pull Request marking them as provided (is this the right scope? I never know) + related changes to make the Integration Tests working again (they currently rely on this)

**Comment by oscerd** [comment]
I think it should be fine. Thanks for your time!
