### ISSUE TITLE
Camel-master: Let's change the gh action to be triggered when a push on master has been done

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#939]
Otherwise it will be a mess to rebase if the job fails multiple times.

**Comment by oscerd** [comment]
After some work I was able to make the backport gh action works on this repository. So now, each time we open a PR on master we need to add the label "backport camel-master" and/or if it is a bug fix for 0.7.x "backport camel-kafka-connector-0.7.x", this will create a PR automatically on the selected branches. 

The rebase job was too buggy because of the docs generation. In this way we should be sure we are backporting the needed bits and then regen the documentation. I removed the rebase camel-master job and I think we should do like the regen job we have on camel.

@valdar @orpiske FYI

**Comment by valdar** [comment]
Ok thanks for the effort in this specially for the LTS branches!

What would be the envisioned work-flow then? Backporting from `master` to `camel-master` then when we align camel version to the new one? merge of `camel-master` in `master`?

**Comment by oscerd** [comment]
Yes

Il lun 1 feb 2021, 09:45 Andrea Tarocchi <notifications@github.com> ha
scritto:

**Comment by orpiske** [comment]
Thanks for this @oscerd! It is really cool and I think it makes it easier for us to make sure the patches go to the right branches at the right time.
