### ISSUE TITLE
S3 source connector delete files from source bucket

### ISSUE THREAD

**Issue by ruchirvaninasdaq** [apache/camel-kafka-connector#97]
I am using the aws-s3 source connector. 

Using this property file:
https://github.com/apache/camel-kafka-connector/blob/master/examples/CamelAWSS3SourceConnector.properties

My messages are been successfully written to Kafka topic, but it deletes the files form s3 bucket. How can I move the processed files to different bucket rather than it gets deleted?

Is there any property that I can use? 

If No, How/Where do I implement that?

**Comment by valdar** [comment]
I fear that at the moment that is not a supported scenario, I think that is not supported by the `camel-aws-s3` component itself. 

It would be a good enhancement proposal.

**Comment by oscerd** [comment]
Yes, we can add an enhancement to the main camel jira

**Comment by ruchirvaninasdaq** [comment]
Hello @valdar & @oscerd ,  I was looking at the aws camel s3 module and found that there is property in onCommit method? Should we extend that in this module? So at least it wont delete the files and I can try implementing the move functionality in aws s3 module later. 

https://github.com/apache/camel/blob/299f0191582df2a8fd376288c5ac8a9c57807adb/components/camel-aws-s3/src/main/java/org/apache/camel/component/aws/s3/S3Consumer.java#L194

Does that make sense?

**Comment by oscerd** [comment]
Yes, I'll raise an enhancement later

**Comment by oscerd** [comment]
https://issues.apache.org/jira/browse/CAMEL-14618

**Comment by oscerd** [comment]
For your information @ruchirvaninasdaq , this has been implemented in Camel 3.3.0, once we upgrade this would be available through the moveAfterRead option

**Comment by ruchirvaninasdaq** [comment]
Thanks, for the update. Please let me know when the kafka-connector moves to camel 3.3.0. I have implemented for now but native support would be nice to have.
Thanks

**Comment by ruchirvaninasdaq** [comment]
@oscerd : What are the timelines for moving to camel 3.3.0? Thank you!!

**Comment by oscerd** [comment]
We should release 0.2.0 during the weekend based on 3.2.0.. after that we should be able to release 0.3.0 based on 3.3.0, probably end of next of week or in a couple of weeks.

**Comment by ruchirvaninasdaq** [comment]
Thank you so much for the update!! 

You are an amazing team!!

**Comment by valdar** [comment]
In `master` this has been fixed by #231. @ruchirvaninasdaq feel free to reopen if it will not be solved once 0.3.0 is released.

**Comment by ruchirvaninasdaq** [comment]
@valdar @oscerd :  Is there an any documentation comparing camel aws vs aws2? What are the difference and benefits of moving to newer version (Aws2)?

**Comment by oscerd** [comment]
More or less Aws2 connectors are equal to aws ones. The difference is in the aws sdk. V2 vs v1. Some of them have some more feature like for example moveAfterRead in Aws2-s3. Basically they are equals in terms of features

**Comment by ruchirvaninasdaq** [comment]
Is there any recommended example of doing message validation (where I can pass class to validate) before putting to the kafka topic?

Currently, I am doing it in aws-camel-s3. Which doesn't seem to be right place. I want to manage that within Kafka-connector project.

**Comment by oscerd** [comment]
Can you post what you are currently doing for validation?

**Comment by ruchirvaninasdaq** [comment]
In S3Enpoint.java class: 

createExchange(ExchangePattern pattern, S3Object s3Object)
`public Exchange createExchange(ExchangePattern pattern, S3Object s3Object) {
        LOG.trace("Getting object with key [{}] from bucket [{}]...", s3Object.getKey(), s3Object.getBucketName());

        ObjectMetadata objectMetadata = s3Object.getObjectMetadata();

        LOG.trace("Got object [{}]", s3Object);

        Exchange exchange = super.createExchange(pattern);
        Message message = exchange.getIn();

        if (configuration.isIncludeBody()) {
            if(verifySchema()){
                message.setBody(s3Object.getObjectContent());
                message.setHeader(S3Constants.SUCCESSFUL_MESSAGE, "true");
            } else {
                Log.error()
                message.setHeader(S3Constants.SUCCESSFUL_MESSAGE, "false");
                message.setBody(null);
            }
        } else {
            message.setBody(null);
        }

        message.setHeader(S3Constants.KEY, s3Object.getKey());
        message.setHeader(S3Constants.BUCKET_NAME, s3Object.getBucketName());
        message.setHeader(S3Constants.E_TAG, objectMetadata.getETag());
        message.setHeader(S3Constants.LAST_MODIFIED, objectMetadata.getLastModified());
        message.setHeader(S3Constants.VERSION_ID, objectMetadata.getVersionId());
        message.setHeader(S3Constants.CONTENT_TYPE, objectMetadata.getContentType());
        message.setHeader(S3Constants.CONTENT_MD5, objectMetadata.getContentMD5());
        message.setHeader(S3Constants.CONTENT_LENGTH, objectMetadata.getContentLength());
        message.setHeader(S3Constants.CONTENT_ENCODING, objectMetadata.getContentEncoding());
        message.setHeader(S3Constants.CONTENT_DISPOSITION, objectMetadata.getContentDisposition());
        message.setHeader(S3Constants.CACHE_CONTROL, objectMetadata.getCacheControl());
        message.setHeader(S3Constants.S3_HEADERS, objectMetadata.getRawMetadata());
        message.setHeader(S3Constants.SERVER_SIDE_ENCRYPTION, objectMetadata.getSSEAlgorithm());
        message.setHeader(S3Constants.USER_METADATA, objectMetadata.getUserMetadata());
        message.setHeader(S3Constants.EXPIRATION_TIME, objectMetadata.getExpirationTime());
        message.setHeader(S3Constants.REPLICATION_STATUS, objectMetadata.getReplicationStatus());
        message.setHeader(S3Constants.STORAGE_CLASS, objectMetadata.getStorageClass());

        /**
         * If includeBody != true, it is safe to close the object here. If
         * includeBody == true, the caller is responsible for closing the stream
         * and object once the body has been fully consumed. As of 2.17, the
         * consumer does not close the stream or object on commit.
         */
        if (!configuration.isIncludeBody()) {
            IOHelper.close(s3Object);
        } else {
            if (configuration.isAutocloseBody()) {
                exchange.adapt(ExtendedExchange.class).addOnCompletion(new SynchronizationAdapter() {
                    @Override
                    public void onDone(Exchange exchange) {
                        IOHelper.close(s3Object);
                    }
                });
            }
        }

        return exchange;
    }`



And within S3Consumer:

`protected void processCommit(Exchange exchange) {
        try {
            if (getConfiguration().isDeleteAfterRead()) {
                String bucketName = exchange.getIn().getHeader(S3Constants.BUCKET_NAME, String.class);
                String key = exchange.getIn().getHeader(S3Constants.KEY, String.class);


                LOG.trace("Deleting object from bucket {} with key {}...", bucketName, key);

                if (exchange.getIn().getHeader(S3Constants.SUCCESSFUL_MESSAGE, String.class).equals("true")) {
                    getAmazonS3Client().copyObject(bucketName, key, getConfiguration().getTargetBucketName(), generateSuccessKey(exchange));

                }
                else {
                    getAmazonS3Client().copyObject(bucketName, key, getConfiguration().getTargetBucketName(), generatefailedKey(exchange));

                }
                getAmazonS3Client().deleteObject(bucketName, key);

                LOG.trace("Deleted object from bucket {} with key {}...", bucketName, key);
            }
        } catch (AmazonClientException e) {
            getExceptionHandler().handleException("Error occurred during deleting object. This exception is ignored.", exchange, e);
        }
    }`

**Comment by oscerd** [comment]
So you're using a customized component. There is actually no mechanism for validating the message before ingesting in kafka topic

**Comment by ruchirvaninasdaq** [comment]
Yeah, as if the messages fails in serialization, it stucks in s3-bucket and keep re-trying. Is there a dead-queue concept in s3 connector?

**Comment by oscerd** [comment]
Currently no.

**Comment by ruchirvaninasdaq** [comment]
Ok thanks!!
