### ISSUE TITLE
MongoDB tests failing with Camel master

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#974]
[tests.log](https://github.com/apache/camel-kafka-connector/files/5925455/tests.log)

Looks like a problem on MongoDB component on Camel, but I need to investigate further.

**Comment by orpiske** [comment]
The problem is caused because the `mongoConnection` is null at this point: https://github.com/apache/camel/blob/camel-3.8.x/components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbEndpoint.java#L235

And it is null at this point because the doStart is not being called for the source connector: https://github.com/apache/camel/blob/camel-3.8.x/components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbEndpoint.java#L323

This works fine for the sink connector.

**Comment by orpiske** [comment]
Opened [CAMEL-16179](https://issues.apache.org/jira/browse/CAMEL-16179) for this issue.

**Comment by orpiske** [comment]
@valdar @oscerd any ideas about how we could fix this?

**Comment by oscerd** [comment]
I don't see an easy way

**Comment by valdar** [comment]
@orpiske the camel issue you mentioned seems to be resolved and included in camel 3.9.0. Is it something needed to review this issue? like enable some previously disable itests?

**Comment by orpiske** [comment]
> @orpiske the camel issue you mentioned seems to be resolved and included in camel 3.9.0. Is it something needed to review this issue? like enable some previously disable itests?

Thanks for the reminder about this. 

I think we need to re-enable the `CamelSourceMongoDBITCase`. Let me do a quick run of that and I'll send a PR soon.

**Comment by orpiske** [comment]
This is working on 0.9.0, and the test was subsequently enabled. Therefore, closing.
