### ISSUE TITLE
Consistent failures in GH tests

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#990]
We are seeing constant failures in Github actions for pull requests caused by the Docker pull limits. 

One thing we could try is upgrading test containers to [1.15.1](https://github.com/testcontainers/testcontainers-java/releases/tag/1.15.1) which solves this problem: 

```Docker 20.10 introduced a new version of the API, 1.41, where they removed quite a few deprecations, and we were using one of them. If you were getting "No such image: testcontainers/ryuk:0.3.0" - that's the cause.```

The challenge here is that Camel 3.7.x is using Testcontainers 1.15.0.

**Comment by orpiske** [comment]
c/c: @valdar @oscerd

**Comment by valdar** [comment]
We can do both :)

**Comment by orpiske** [comment]
Thanks folks, it seems that the recent problems on GH tests have been fixed. I am closing this one for now.
